### ISSUE TITLE
Do we need AMD Graphic card for using AMD ProRender?

### ISSUE THREAD

**Issue by madoodia** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#1]
Hey guys
I saw your presentation in SIGGRAPH 2018 in Vancouver, I liked the way you integrated your renderer into USD.
We installed USD on our linux box in studio and want to try to use RadeonProRender.
There are two question:
1. Where exactly we should get the SDK and what is contact information of AMD?
2. We should have AMD Graphic card to use this renderer or it is ok with nVidia Products too? (I'm Asking Because you said it is created by OpenCL, so it should be Hardware Agnostic)

thanks

**Comment by bsavery** [comment]
Hi there.  As I mentioned in the presentation, any OpenCL 1.2 supporting card should be ok.  We certainly encourage AMD cards though!  But any modern mid-high end and most professional level cards work.

We can give access to the DLL's needed to compile this library if needed.  Email brian.savery@amd.com

**Comment by madoodia** [comment]
Great
I just see the slides
Thanks Brian, i'll send email for you
