### ISSUE TITLE
Consider implementing interactive mode

### ISSUE THREAD

**Issue by hshakula** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#102]
For example in Houdini when you move camera it sets RenderSetting "interactive" to true, which we can process and enable interactive mode

**Comment by bsavery** [comment]
What does this mean?  "Interactive Mode"?  Also what would we do on the RPR side with this setting?

**Comment by hshakula** [comment]
Many renderers implement interactive modes in a different fashion, but the main idea is to drastically increase frame render time while a user interacts with the scene. What can we do for example:
1. Decrease max recursion parameter.
2. Increase pixel size effectively decreasing the number of rays per sample

**Comment by hshakula** [comment]
Decreasing max recursion looks just fine. Implemented in #128
