### ISSUE TITLE
swapping delegates between RPR and Karma results in a Crash

### ISSUE THREAD

**Issue by fralumz** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#157]
When the scene contains a previewsurface using textured displacement, swapping from RDR to karma results in a crash.
[crash.rdpr_crash.Jon_Mack_28456_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3899886/crash.rdpr_crash.Jon_Mack_28456_log.txt)
[rdpr_crash.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3899894/rdpr_crash.zip)

**Comment by hshakula** [comment]
Hi, I tried to reproduce but I didn't make it. I see no displacement texture provided in displacement usduvtexture, so actually displacement node has no effect here. Could you please make sure that my materiallibrary matches with yours?
![image](https://user-images.githubusercontent.com/22181845/69803701-8254cd00-11e5-11ea-9f86-f0c9453795e2.png)

**Comment by fralumz** [comment]
I didn't include the texture I was using.  It's one of the bundled textures 'rocks001_height.rat' converted to exr.  It should be the same with any texture.

**Comment by hshakula** [comment]
I believe that I have found the reason for the crash you caught.
Here is an updated package [hdRpr-Houdini-1.0.1-Windows.tar-package](https://drive.google.com/open?id=1Jwrcf56CJdp0EsvDC7PaOgvZmcQfhdda). Please, could you try and verify the absence of this particular issue?

Also, I see that mesh with displacement look differently in RPR and Karma, I have created an appropriate issue here #169 

P.S. hdRpr supports .rat images in case you were converting to exr especially for hdRpr
