### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by simonohler** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#161]
Hi,
we are running CentOS 7 with GLIBC_2.17. The plugin seems to require GLIBC_2.27.
It would be great if you could also provide a compiled version for CentOS 7!

Cheers,
Simon

**Comment by bsavery** [comment]
We haven't officially tested that yet. We'll see if we can do that next week.  You can actually compile the plugin from the source here if you have that capacity.  But we'll take a look at adding a centos 7 version

**Comment by simonohler** [comment]
That would be great! Thanks!

**Comment by bsavery** [comment]
Centos 7.6 would be ok?

**Comment by simonohler** [comment]
Yes that should work for us!

**Comment by hshakula** [comment]
Hi, could you please try this [build](https://drive.google.com/file/d/19ii4OVlZSMAeU69xHylm_jaTZ1_Djbv7/view?usp=sharing)? Thank you

**Comment by simonohler** [comment]
Thanks for compiling it! Unfortunately I am getting an error when switching to RPR in Houdini:

TfDlopen: [opening] '/opt/hfs18.0.313/dsolib/usd_plugins/hdRpr.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.313/dsolib/usd_plugins/hdRpr.so' (handle=(nil))
TfDlopen: [error on opening] '/opt/hfs18.0.313/dsolib/usd_plugins/hdRpr.so': libRadeonImageFilters64.so.1.4.2: cannot open shared object file: No such file or directory

**Comment by simonohler** [comment]
For some reason it didn't work when installed to /opt/hfs18.0.313:
TfDlopen: [error on opening] '/opt/hfs18.0.313/dsolib/usd_plugins/hdRpr.so': libRadeonImageFilters64.so.1.4.2: cannot open shared object file: No such file or directory

So I copied the files to my user folders /houdini18.0/dso/ directory. Now it works!
I'll do some testing and report back if I run into any other issues.

Thanks a lot for compiling!

**Comment by hshakula** [comment]
Great, but it strange that installer didn’t do his job, it works just fine on Ubuntu, I will investigate it. Could you please contact me in discord - hshakula#1497 - or by email - georgeshakula@gmail.com. I want to ask you more about Houdini setup on centos. For me right now houdini instantly crashes when I switch to “stage”

**Comment by hshakula** [comment]
Hi, @simonohler, could you please try the latest release?
