### ISSUE TITLE
popOS! (Ubuntu) crash when switching to RPR viewport

### ISSUE THREAD

**Issue by kubo-von** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#162]
Installed RPR with the install.py, all went smooth, I can see the RPR in the viewport menu, but when trying to enable it, even on empty stage, it crashes evey time. 

`Crash report from me; Houdini Version 18.0.287 [linux-x86_64-gcc6.3]
Uptime 14 seconds
Fri Nov 29 20:59:22 2019
Caught signal 11

Traceback from 17452 ThreadId=0x7f88a5a91700
AP_Interface::si_CrashHandler::handledSignal(UTsignalHandlerArg) <libHoudiniUI.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
__funlockfile <libpthread.so.0>
__nss_database_lookup <libc.so.6>
pxrInternal_v0_19__pxrReserved__::HdRprApiAov::GetDataImpl(void*, unsigned long) <hdRpr.so>
pxrInternal_v0_19__pxrReserved__::HdRprApiAov::GetData(void*, unsigned long) <hdRpr.so>
pxrInternal_v0_19__pxrReserved__::HdRprApi::Render(pxrInternal_v0_19__pxrReserved__::HdRprRenderThread*) <hdRpr.so>
pxrInternal_v0_19__pxrReserved__::HdRprApi::Render(pxrInternal_v0_19__pxrReserved__::HdRprRenderThread*) <hdRpr.so>
bool __gnu_cxx::__ops::_Iter_pred<pxrInternal_v0_19__pxrReserved__::HdRprApiImpl::RenderImage(std::string const&)::{lambda(pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding const&)#1}>::operator()<__gnu_cxx::__normal_iterator<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding*, std::vector<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding, std::allocator<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding> > > >(__gnu_cxx::__normal_iterator<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding*, std::vector<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding, std::allocator<pxrInternal_v0_19__pxrReserved__::HdRenderPassAovBinding> > >) [clone .isra.573] <hdRpr.so>
pxrInternal_v0_19__pxrReserved__::HdRprRenderThread::RenderLoop() <hdRpr.so>
QWebEngineUrlSchemeHandler::qt_metacall(QMetaObject::Call, int, void**) <libQt5WebEngineCore.so.5>
start_thread <libpthread.so.0>
__clone <libc.so.6>

Traceback from 17452 ThreadId=0x7f893d090c80
AP_Interface::coreDumpChaser(UTsignalHandlerArg) <libHoudiniUI.so>
AP_Interface::si_CrashHandler::chaser(UTsignalHandlerArg) <libHoudiniUI.so>
signalCallback(UTsignalHandlerArg) <libHoudiniUT.so>
UT_Signal::UT_ComboSignalHandler::operator()(int, siginfo_t*, void*) const <libHoudiniUT.so>
UT_Signal::processSignal(int, siginfo_t*, void*) <libHoudiniUT.so>
__funlockfile <libpthread.so.0>
__sched_yield <libc.so.6>
_nv043glcore <libnvidia-glcore.so.440.31>
_nv043glcore <libnvidia-glcore.so.440.31>
_nv003glcore <libnvidia-glcore.so.440.31>
_nv023glcore <libnvidia-glcore.so.440.31>
UI_Viewport::getColorTexture(RE_Render*) <libHoudiniUI.so>
DM_VPortAgent::compositePasses(RE_Render*, GUI_DisplayOption const*, bool, bool) <libHoudiniAPPS3.so>
DM_VPortAgent::renderSceneView(RE_Render*, int, int) <libHoudiniAPPS3.so>
DM_VPortAgent::renderViewport(RE_Render*, int, int) <libHoudiniAPPS3.so>
DM_VPortAgent::doRender(RE_Render*, int, int) <libHoudiniAPPS3.so>
DM_Viewport::doRender(RE_Render*, int, int) <libHoudiniAPPS3.so>
UI_Feel::renderMe(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRenderKids(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRender(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::renderMe(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRenderKids(RE_Render*, int, int) <libHoudiniUI.so>
UI_Feel::doRender(RE_Render*, int, int) <libHoudiniUI.so>
UI_Viewport::reRender(RE_Render*, bool) <libHoudiniUI.so>
UI_Window::renderChildViews(RE_Render*) <libHoudiniUI.so>
UI_Window::doRedrawSubclass() <libHoudiniUI.so>
dm_ViewLayoutWindow::doRedrawSubclass() <libHoudiniAPPS3.so>
UI_Window::doRedraw() <libHoudiniUI.so>
UI_Queue::doWindowRedraws() <libHoudiniUI.so>
UI_Queue::drain() <libHoudiniUI.so>
UI_Queue::eventLoop() <libHoudiniUI.so>
main <libHoudiniUI.so>
__libc_start_main <libc.so.6>
main <hindie-bin>
`

**Comment by bsavery** [comment]
What is your GPU?

**Comment by kubo-von** [comment]
GeForce GTX 1050TI 4G

**Comment by hshakula** [comment]
Some info so far:
* OS version - 19.10
* Crash report -  [crash.untitled.colin_23211_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3922130/crash.untitled.colin_23211_log.txt)

Might be related to the fact that RPR supports Ubuntu no higher than 18.04.
I need to setup Ubuntu 19.10 and try to reproduce this issue.

**Comment by eqcq** [comment]
it crashes the same way on osx 10.14 with a Radeon Pro WX 9100 16 Go

**Comment by hshakula** [comment]
Hi, try this build please https://drive.google.com/open?id=1_-s8KT5laaK81VQAADbuSUCHhnG9QN9Q

**Comment by eqcq** [comment]
Thanks, I try to setup in terminal and : 
"hdRpr-1.1.20-Houdini-18.0.391-macOS.tar.gz": unknown target. Skipping.
Could not find any packages to install

**Comment by hshakula** [comment]
Fixed https://drive.google.com/open?id=1itWvOK64NyV4eealC4PsQAj0XPd6i0fz

**Comment by eqcq** [comment]
Thanks Georges, you are so quick. Everything looks working like a charm

**Comment by hshakula** [comment]
btw, what Houdini version do you use right now?

**Comment by eqcq** [comment]
Houdini-18.0.391

**Comment by kubo-von** [comment]
Fixed for me too, works in hdRpr-1.2.2-Houdini-18.0.460
