### ISSUE TITLE
Exception, e: issue.

### ISSUE THREAD

**Issue by cabraswel** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#163]
C:\Users\manta\Desktop\prorender>python install.py
  File "install.py", line 37
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by bsavery** [comment]
This happens because you're using python 3 to install.  We assumed it would be installed with python 2.7.  But we updated the install script.  You can get that here:

Just replace the install.py file with this.
[install.py.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3906526/install.py.zip)

**Comment by cabraswel** [comment]
> This happens because you're using python 3 to install. We assumed it would be installed with python 2.7. (because of the vfx platform requirements) But we updated the install script. You can get that here:
> 
> Just replace the install.py file with this.
> [install.py.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3906526/install.py.zip)

I resolved this and used the -i argument to fix my H18 install dir for Steam.

But do I need to do something else? The program crashed after I changed the Hydra display to RPR.

**Comment by cabraswel** [comment]
> This happens because you're using python 3 to install. We assumed it would be installed with python 2.7. (because of the vfx platform requirements) But we updated the install script. You can get that here:
> 
> Just replace the install.py file with this.
> [install.py.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3906526/install.py.zip)

Thank you. This works. I was able to get it all to work. Is there a RPR node similar to the Karma node in the LOPs operators? I can only manage to get the viewport to render.

**Comment by hshakula** [comment]
Do you mean "Karma Render Properties"?

We don't have custom nodes for Houdini yet. But I already thought about that it would be nice to have such a node as "Karma Render Properties" (#142). Just had no time for it yet
