### ISSUE TITLE
Camera Focal length missmatch Karma/RPR

### ISSUE THREAD

**Issue by nrdpxl** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#164]
I have a weird issue with camera focal length, switching between Karma and RPR they do not match. (screenshots and scene file attached)

<img width="2032" alt="lopnet_Karma" src="https://user-images.githubusercontent.com/3891361/69901254-1a35f080-1377-11ea-8792-50998e59ef9f.png">
<img width="2032" alt="lopnet_RPR" src="https://user-images.githubusercontent.com/3891361/69901255-1ace8700-1377-11ea-8b25-f7063373f2fc.png">
<img width="2032" alt="stage_Karma" src="https://user-images.githubusercontent.com/3891361/69901256-1ace8700-1377-11ea-85eb-dd1264250dc5.png">
<img width="2032" alt="stage_RPR" src="https://user-images.githubusercontent.com/3891361/69901257-1ace8700-1377-11ea-9777-0947dc0c2019.png">
[RPR_Test_01.hiplc.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3907147/RPR_Test_01.hiplc.zip)

**Comment by fralumz** [comment]
If you resize the pane so that the image vertical fits top to bottom, then it will match.  I'm seeing this issue in all of the non-karma, non-houdiniGL delegates as well.  It seems there is some sort of hydra issue with passing right render window.

**Comment by bsavery** [comment]
This sounds like maybe it should be raised to SideFX if its the same for all Delegates.  We'll consolidate all the issues we have and sync up with them.

**Comment by nrdpxl** [comment]
I will report this issue to SideFX too.

**Comment by hshakula** [comment]
Let me check it tomorrow first, and if I will not find the bug here then we report to SideFX

**Comment by hshakula** [comment]
Orthographic projection does not match also when using the Camera node, but when you look through native viewport camera (in all view types: image, top, bottom, etc) RPR result does match to Karma. Interesting.

Unfortunately, Storm does not render anything on my machine, but I tested this scene also in a custom build of Embree delegate - same camera as in RPR and 3Delight.

**Comment by hshakula** [comment]
I see what Karma is doing. This issue is going to be fixed soon
