### ISSUE TITLE
Windows 10 install.bat not working

### ISSUE THREAD

**Issue by FazFD** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#166]
Hope I'm not missing something obvious, unzipped the files into a folder on the desktop and run install.bat as administrator. I get this:

![install bat result](https://user-images.githubusercontent.com/58393363/69915277-370e1900-1488-11ea-96bf-27b8c2c23e2d.JPG)

After I press any key it closes immediately and doesn't seem to have done anything. I only have Houdini GL, Karma and Storm available.

Do I need python installed? Are there any other prerequisites?

**Comment by hshakula** [comment]
Looks like you already have python in your `PATH`, so it's not the source of the problem. Let's find out the reason.

Can you please open `Command prompt` and try the following:
1. cd to unzipped package dir (in your case `cd C:\Users\Faz\Desktop\hdRpr-Houdini-1.0.0-win64`)
2. and run `python install.py -p hdRpr-Houdini-1.0.0-win64.zip`

**Comment by FazFD** [comment]
[image: python install.JPG]
Thanks for replying so quickly.

**Comment by hshakula** [comment]
Your image is broken

**Comment by FazFD** [comment]
Sorry not sure what happened

**Comment by hshakula** [comment]
What is the output of `python --version`?

**Comment by FazFD** [comment]
Sorry I don't normally do command line stuff, 
I get nothing when I use python --version
The same as when I try to use python install.py

**Comment by hshakula** [comment]
Okay, then it really seems you don't have python installed or something wrong with your environment. So I can propose two ways of resolving this issue:
1. Manually copy needed files - unzip `hdRpr-Houdini-1.0.0-win64.zip` and copy `bin` and `houdini` folders to your Houdini installation dir (e.g. `C:\Program Files\Side Effects Software\Houdini 18.0.287`). Should work after it.
2. Make sure that you have installed python or install it otherwise. Try again install.bat

**Comment by FazFD** [comment]
Thanks for your help and patience ! It worked.
Just a suggestion: You might want to mention in the install instructions at https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/releases that there needs to be a python install with an environment variable setup. It might seem obvious to most technical Houdini users but there will probably be more people running into the same problem when people start to realize that there is a free GPU render to be had,

**Comment by hshakula** [comment]
Thank you for your suggestion. I made some changes to INSTALL.md in [7ecb6d6](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/7ecb6d6898105f7b0bfb96f5e940563d4fb64185/INSTALL.md), this will subsequently be present on the releases page. It looks more understandable for you?

P.S. Actually you have a strange command prompt, typically if you have no python, on an attempt to run it you would get something like:
```
'python' is not recognized as an internal or external command,
operable program or batch file.
```
But we've seen that you had no output at all. Very interesting

**Comment by FazFD** [comment]
Thanks, yes that is much more clear,
Yeah that cmd prompt thing is weird, I swear I'm cursed with things like that
