### ISSUE TITLE
Mesh doublesided attribute is not supported

### ISSUE THREAD

**Issue by hshakula** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#183]

**Comment by bsavery** [comment]
I saw from the other thread:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/182 that you tried the doublesided node.  That would be my suggestion.

**Comment by hshakula** [comment]
I have added this issue because it would be good to support it but regarding #182 I have tried using two-sided material node but it didn't help, there is something deeper

**Comment by hshakula** [comment]
From RPR perspective all materials are double-sided by default, but they behave differently on front face and back face. Is it expected behavior? Should not they be the same? Imagine mesh that consists of one triangle, in RPR it would look different depending on the viewport position.
Here is what I'm talking about, please have a look:
[materialInconsistency.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3955754/materialInconsistency.zip)

**Comment by hshakula** [comment]
In the latest RPR, RPR_MATERIAL_NODE_TWOSIDED actually inverse normal on back face, so we can actually use this node to add some sort of double-sidedness
