### ISSUE TITLE
Windows installer giving errors!

### ISSUE THREAD

**Issue by nick-clicks** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#192]
Hi , the Windows installer is giving me several errors

1. Line 37 -except Exception, e:

    I removed the ", e" and got past that one, to get: 

2. C:\Users\nick_\Documents\houdini18.0>python install.py
Installing "hdRpr-Houdini-1.0.0-win64.zip"
Few Houdini installation has been found. Select the desired one.
0. "C:\Program Files\Side Effects Software\Houdini 17.5.229"
1. "C:\Program Files\Side Effects Software\Houdini 16.5.571"
2. "C:\Program Files\Side Effects Software\Houdini 18.0.315"
3. "C:\Program Files\Side Effects Software\Houdini 17.5.397"
Enter number.
Traceback (most recent call last):
  File "install.py", line 140, in <module>
    i = int(raw_input())
NameError: name 'raw_input' is not defined

this one is beyond my no existent python knowledge! 
If you could help me to get the installer working so I could try ProRender out that would be great.

Thanks

**Comment by hshakula** [comment]
Hi, please replace your install.py with the [latest](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/master/pxr/imaging/plugin/hdRpr/package/install.py)

We need to post a new release with recent fixes

**Comment by hshakula** [comment]
Also, there is no reason to consider Houdini installations with major version less than 18, I will fix it

**Comment by nick-clicks** [comment]
I Still had errors untill i changed 

   input = raw_input

to be 

   raw_input = input

Now it works! Thank you for your help.

**Comment by hshakula** [comment]
What is the version of your python?
You can get it from cmd prompt by running python --version

**Comment by edschiffer** [comment]
I'm having the same issues, assuming it's because I also have Python 3 installed. Currently looking for a way to use 2.7 for the installation.

**Comment by hshakula** [comment]
Hi, we are planning to make a new release this week, this issue would be eliminated
In the meantime, I just have built a package from the latest master, tested with python 3.8.0
https://drive.google.com/file/d/15iLOm9w6-qlHJ9jJqXxY9HNIxk5z5DWx/view?usp=sharing

**Comment by edschiffer** [comment]
Oh, highly appreciated. Thanks!
I just had to run the .bat as Admin and it installed fine.

**Comment by hshakula** [comment]
@nick-clicks, @edschiffer 
Could you please confirm that this issue has been resolved with the latest release?

**Comment by nick-clicks** [comment]
Hi , just installed a fresh Houdini 18.0.327 from the daily builds and the the latest ProRender download, and it all installed smoothly. 
much appreciated Thanks.
