### ISSUE TITLE
'RadeonProRender_Baikal.h' file not found

### ISSUE THREAD

**Issue by fabz011** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#220]
I am missing a file when I build on MacOS using the latest commit (1.1.3). Am I doing something wrong?

make install

[ 30%] Built target hdRpr_headerfiles
Scanning dependencies of target hdRpr
[ 31%] Building CXX object pxr/imaging/plugin/hdRpr/CMakeFiles/hdRpr.dir/rprApi.cpp.o
/Users/binserver/Downloads/RadeonProRenderUSD-master2/pxr/imaging/plugin/hdRpr/rprApi.cpp:31:10: fatal error: 
      'RadeonProRender_Baikal.h' file not found
#include <RadeonProRender_Baikal.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [pxr/imaging/plugin/hdRpr/CMakeFiles/hdRpr.dir/rprApi.cpp.o] Error 1
make[1]: *** [pxr/imaging/plugin/hdRpr/CMakeFiles/hdRpr.dir/all] Error 2
make: *** [all] Error 2

**Comment by fabz011** [comment]
Could it be related to the fact I am using Radeon Pro Render SDK 1.34.2 ?
Requirements are for 1.34.5 or higher but the AMD website link provides you only with the version I have

**Comment by hshakula** [comment]
That's absolutely related to the fact that the SDK page provides the old version. As a temporary solution, I can provide you with needed [SDK](https://drive.google.com/file/d/1sB9INe-S5sMd0_7Bpy9-15OnfY61unEw/view?usp=sharing)

**Comment by hshakula** [comment]
And here is the latest [RIF SDK](https://drive.google.com/open?id=1eS79VSAlxrBZJO-J7WqcWzTFOUfzFuT_)

**Comment by fabz011** [comment]
Oh brilliant! Thanks George

**Comment by bsavery** [comment]
Fixed with public apis.
