### ISSUE TITLE
Could someone help me to install Prorender in Houdini?

### ISSUE THREAD

**Issue by ArkFlyl9** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#226]

**Comment by hshakula** [comment]
You will need to tell me first what you have already done and what (from INSTALL.md) causes trouble for you

**Comment by ArkFlyl9** [comment]
Hi,

I had only download this file "hdRpr-Houdini-1.1.0-Windows-package.zip", I thought just executing the "install.bat" would work. The terminal appeared, asked me to press a key to continue but then it closed and nothing happened

But I now, reading the file you mentioned, tried the manual method without success, I copied the files to the Houdini folder. 

Kind regards, 
Arturo

**Comment by hshakula** [comment]
Do you have python installed on your machine (with modified PATH)?

**Comment by ArkFlyl9** [comment]
I have it, though I don't understand what you mean by modified PATH...

**Comment by hshakula** [comment]
Open cmd prompt and run ’python --version’
You should see some valid output

**Comment by ArkFlyl9** [comment]
Thanks !! 

I got it running, it seems python was not correctly installed or I had a very old version, I tried the newest version of Python
