### ISSUE TITLE
Uber Shader / Material Library

### ISSUE THREAD

**Issue by cabraswel** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#227]
Is there a way in the current version to get access to this "https://radeon-pro.github.io/RadeonProRenderDocs/uber/about.html"

Or is there a way to use the existing Shaders for things like SSS that appear to be supported in the render engine but not available in the plugin.

**Comment by hshakula** [comment]
Unfortunately, there is no way to do it now but we are planning [MaterialX](https://www.materialx.org) support which would cover all render engine capabilities and even more

Right now our material system complies USD’s [UsdPreviewSurface proposal](https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html)

**Comment by bsavery** [comment]
Just to add a bit... USD Preview Surface in hdRPR actually uses Uber under the hood when rendering.  It just uses a simplified user interface that USD standardizes on.

**Comment by cabraswel** [comment]
I have attempted to use the USD Preview Surface node and the sliders and parameters have not been functioning all the time. The color updates but changes to metallic, roughness, etc etc update in the render sometimes and other times the sharers do not update at all.

**Comment by bsavery** [comment]
Can you give us a repro case to take a look at?

**Comment by cabraswel** [comment]
Log it as an "issue"? I don't have a case.
