### ISSUE TITLE
VDBs and Shadow Catcher

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#233]
Hi,

I've been using the RPR plugin and for the most part I've figured out how to use it as well as figuring USD at the same time. Just a couple things I can't figure out for the life of me:

1. VDBs that are imported from the /obj context never seem to work for me even when adding the "usdvolumepath" attribute (although I could definitely be setting that incorrectly), what is the workflow to be able to render VDBs?
2.  How do you create a shadow catcher like the RPR plugin can in other 3D packages?

Thanks in advance and thank you for bringing this to Houdini!

**Comment by hshakula** [comment]
Hi, I'm glad to hear that you are (mostly) satisfied with RPR.
1. I'm not sure about it. Can you drop me a sample .hip file with your vision of how it should work? I will test it and figure out what is going wrong
2. There is no established pipeline for that in perspective of USD's Hydra, at least the one I know about. If you have information about it or if you would encounter it in other plugins in the future I would appreciate if you share

**Comment by AlxndrTheWretch** [comment]
Thanks for your reply @hshakula ,

1. Here's a hip file and a screenshot of what I get in case it is different for you lol
[VDB.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4155188/VDB.zip)

2. Okay, not even to do a shadow matte or something like that?

**Comment by hshakula** [comment]
Hey, @AlxndrTheWretch, in the latest builds we improved VDB support and added shadow/reflection catchers. Would you mind giving it a try? Here's a build [hdRpr-1.2.7-Houdini-18.0.460-Windows.tar.gz](https://drive.google.com/file/d/1MU17zkq4gatXRy5fAwSRP6orCcApZwRZ/view?usp=sharing)

**Comment by AlxndrTheWretch** [comment]
Hi @hshakula, thank you for this! But it seems that when I switch to preview render, Houdini crashes with this version with Houdini build 499 onward

**Comment by hshakula** [comment]
Hi, I've just checked the build I gave you with Houdini 499 and I cannot reproduce the crash. Do you have Houdini's crash log?
![image](https://user-images.githubusercontent.com/22181845/86283536-f034fd00-bbe9-11ea-8e7c-5f5c09e005a2.png)

**Comment by AlxndrTheWretch** [comment]
It doesn't seem to be generating a crash log in the AppData\Local\Temp\houdini_temp folder, I don't know if that is where to look. I did manage to get this from the console before one crash 
![image](https://user-images.githubusercontent.com/51461775/86286060-c7921080-bbb3-11ea-9cde-98ffc23a0bb4.png)

**Comment by hshakula** [comment]
This does not seem related to hdRpr, Houdini does not crash with any other delegate?

**Comment by AlxndrTheWretch** [comment]
No, I tried karma, renderman, and 3Delight. Is there something I should try reinstalling? I already tried reinstalling Houdini

**Comment by hshakula** [comment]
1. Do you see the same output in console with any other delegate? I mean `TypeError: unbound method ...`
2. Let's try the build I compiled against Houdini 499 - [link](https://drive.google.com/file/d/1YQz2t7qiIGwMJ1EZo4u8Gonaie5oraOL/view?usp=sharing). You will need either remove the previous plugin or deactivate it (in the same way you activated it, just with a flag `-d`: `python activateHoudiniPlugin.py -d`)

**Comment by AlxndrTheWretch** [comment]
Okay, so it seems to be my computer because I tried it on another one and it's working fine....weird. So in terms of shadow matte, reflection matte etc. do you know what the name of them is in USD? Like how color is Ci? I can't find anything on that.

VDBs are looking way better!

**Comment by hshakula** [comment]
> Okay, so it seems to be my computer because I tried it on another one and it's working fine....weird.

Nice to hear but it would be nice to get it working on the first PC either. What's the hardware setup is there?

> So in terms of shadow matte, reflection matte etc. do you know what the name of them is in USD? Like how color is Ci? I can't find anything on that.

As far as I know, there is no convention in USD related to this topic. Here's a [modified scene](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4866739/scene.zip) I was sending you before. You will find two major changes inside:
1. The material of the plane
  ![image](https://user-images.githubusercontent.com/22181845/86411065-ad942300-bcc4-11ea-9a28-920c61f0308d.png)

2. Render Var and Render Product nodes to view shadow and reflection catchers AOV
  ![image](https://user-images.githubusercontent.com/22181845/86411162-e7652980-bcc4-11ea-982c-c99974d96810.png)
  ![image](https://user-images.githubusercontent.com/22181845/86411185-f350eb80-bcc4-11ea-8e48-44bebc425cd9.png)

And here is how it looks for me:
* rawColor
![image](https://user-images.githubusercontent.com/22181845/86411257-20050300-bcc5-11ea-8699-9276c1091a58.png)

* reflectionCatcher
![image](https://user-images.githubusercontent.com/22181845/86411305-3ca13b00-bcc5-11ea-89af-968095db1f14.png)

* shadowCatcher
![image](https://user-images.githubusercontent.com/22181845/86411268-26937a80-bcc5-11ea-9b0a-e1bb5582106c.png)

Also before trying it, replace the build with [this one](https://drive.google.com/file/d/17PSmN1dzZmUICZpBYM84QnOeYrfzUfwc/view?usp=sharing)

**Comment by AlxndrTheWretch** [comment]
So in regard to the first PC, it is running two 2080ti's and now that I am thinking about it, I think the problems started when I installed the second GPU. The PC it is working on only has one Radeon VII, maybe it's the multi-GPUs?

**Comment by hshakula** [comment]
It's possible because in hdRpr we always activate all available GPUs. I can make a build that will use only the first GPU, would you mind testing it?

**Comment by AlxndrTheWretch** [comment]
Sure thing. I mean it would be ideal for it to use all GPUs.

**Comment by hshakula** [comment]
Well, I just want to make sure that this issue is multi-GPU related

**Comment by hshakula** [comment]
Ideally, you should be able to select active GPUs but I still had no time to check how can I generate LOP node from code that will control active GPUs

**Comment by AlxndrTheWretch** [comment]
In the render settings node you mean?

**Comment by hshakula** [comment]
Yeah, you can see that currently, you can only select between GPU and CPU but you can't control your devices in any more comprehensive manner.
![image](https://user-images.githubusercontent.com/22181845/86937574-13aafb00-c148-11ea-83c6-62326be62a43.png)

**Comment by hshakula** [comment]
What about the original issue - vdbs and shadow catcher. Do you have any questions about it or this issue can be closed?
Let's move our discussion about the crash [here](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/303)

**Comment by AlxndrTheWretch** [comment]
I'm not sure why but I'm not seeing the materials that your screenshots have. Here's what I see: (I did set the rendersettings2 node to CPU as that seems to work in regard to the GPU issue lol)
![image](https://user-images.githubusercontent.com/51461775/86944144-530c2400-c115-11ea-8394-d87fb5cb44a7.png)

**Comment by hshakula** [comment]
Material nodes are inside of `Material Library` LOP node

**Comment by AlxndrTheWretch** [comment]
Right, I'm just  not sure why it isn't showing up correctly

**Comment by hshakula** [comment]
Hm, wait you don't see the RPR tab when you are inside of `Material Library`, is that correct?
![image](https://user-images.githubusercontent.com/22181845/86945055-3988cd80-c151-11ea-87ad-7f5b33273a1a.png)

**Comment by AlxndrTheWretch** [comment]
No I see it
![image](https://user-images.githubusercontent.com/51461775/86945448-06294d00-c117-11ea-84a1-ad051f489ba8.png)

**Comment by hshakula** [comment]
So what did you mean by saying "isn't showing up correctly"?

**Comment by AlxndrTheWretch** [comment]
So comparing your screenshot to mine, there's reflection in your grid not in mine. And more relevant to the issue, the AOVs aren't showing up even the shadow catcher one:

![image](https://user-images.githubusercontent.com/51461775/86946214-0fff8000-c118-11ea-9fde-bc631d9561de.png)

**Comment by hshakula** [comment]
So if this is how you see the scene that I've sent
![image](https://user-images.githubusercontent.com/51461775/86944144-530c2400-c115-11ea-8394-d87fb5cb44a7.png)
then I can conclude that neither sphere nor grid has materials at all. This also explains why reflectionCatcher and shadowCatcher AOVs are blank.

Let's figure why materials are not working.
What do you see on this scene [uberTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4892212/uberTest.zip)?

**Comment by AlxndrTheWretch** [comment]
This:

![image](https://user-images.githubusercontent.com/51461775/86951002-f0b82100-c11e-11ea-9bba-47f9d37bda03.png)

**Comment by hshakula** [comment]
Hm, interesting, okay this behavior is consistent for all material. Could you please run Houdini with `TF_DEBUG` environment variable set to `TF_PRINT_ALL_POSTED_ERRORS_TO_STDERR` - this will do exactly what it says, we need it because Houdini hides errors/warnings coming from USD libraries.

If you don't know how to do it, you can do it like this:
* run Houdini's `Command Line Tools` application
* run `set TF_DEBUG=TF_PRINT_ALL_POSTED_ERRORS_TO_STDERR` command
* run `houdinifx` command
* after this you should see opening Houdini app, just open any .hip I sent you with RPR or UsdPreviewSurface material, I'm interested in the output of "Houdini Console"

**Comment by AlxndrTheWretch** [comment]
So  these two popped up:

![image](https://user-images.githubusercontent.com/51461775/86953336-4b9f4780-c122-11ea-9d3b-103edaeefb5a.png)
![image](https://user-images.githubusercontent.com/51461775/86953356-53f78280-c122-11ea-95fb-ad7a44a25507.png)

**Comment by hshakula** [comment]
These two are unrelated to the current issue.

Repeat steps from the previous message but set `TF_DEBUG` to `RPR_USD_DEBUG_DUMP_MATERIALS` instead of `TF_PRINT_ALL_POSTED_ERRORS_TO_STDERR`. 
- run `set TF_DEBUG=RPR_USD_DEBUG_DUMP_MATERIALS` command

This will save material networks for each material in the current working directory (CWD). You can find out the CWD here:
![image](https://user-images.githubusercontent.com/22181845/87039117-5d065380-c1f7-11ea-94f0-e85886432d56.png)

Now if you open the scene with uber or UsdPreviewSurface materials you should see a file with name matching to material primitive name. It will show us if Houdini gives any materials to hdRpr at all.

**Comment by AlxndrTheWretch** [comment]
I loaded both scenes and there doesn't appear to be any files in that directory

**Comment by hshakula** [comment]
[sceneUPS.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4896771/sceneUPS.zip)
What do you see with this scene? Any files created in CWD (it should have `_materials_usdpreviewsurface1` name on this scene)? 

And I just want to make sure you run Houdini from the terminal in which you set the `TF_DEBUG` environment variable, are you?

**Comment by AlxndrTheWretch** [comment]
Still nothing, it would be in that exact directory right? Not a subdirectory?

Yes I am.

**Comment by hshakula** [comment]
It should be in that exact directory
![image](https://user-images.githubusercontent.com/22181845/87041934-a35db180-c1fb-11ea-92f8-38b109ca952f.png)

Well, that is really weird, let me drop some more logging to see what's happening on your side. I will send you another build.

**Comment by AlxndrTheWretch** [comment]
Yeah, there's nothing like that there

**Comment by hshakula** [comment]
[New build](https://drive.google.com/file/d/10ClP70j4pBfJZ9DhDF49E-81ed3r4poz/view?usp=sharing). Just replace the content of the currently active package wit it.

The expected output in the console for the latest scene:
![image](https://user-images.githubusercontent.com/22181845/87042550-7eb60980-c1fc-11ea-8629-613d48f0df54.png)

**Comment by AlxndrTheWretch** [comment]
So I found out that I had a incomplete install of USD in my system that my environment variables were set to so I removed that and now everything is working. Sorry about that and thank you for your patience, I'll close this issue and the multi-GPU issue is still happening :)
