### ISSUE TITLE
Debian 10 support

### ISSUE THREAD

**Issue by habernir** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#235]
hi there 
i just install prorender for houdini (ubuntu 18.04) on debian 10
but when i go the solaris mode and click on "RPR"
its doesn't do anything and the "RPR" dissapear 

thanks 
nit

**Comment by hshakula** [comment]
Problem is in glibc version mismatch
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/230

**Comment by hshakula** [comment]
Anyway, let's try to figure out your exact problem.
Could you please follow this https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/230#issuecomment-581445665?

**Comment by habernir** [comment]
this is the output:

TfDlopen: [opening] '/opt/hfs18.0.348/houdini/dso/usd/USD_Plugins.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/houdini/dso/usd/USD_Plugins.so' (handle=0x7f07f35bdd00)
TfDlopen: [opening] '/opt/hfs18.0.348/dsolib/libpxr_usd.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/dsolib/libpxr_usd.so' (handle=0x7f089bf0ef50)
TfDlopen: [opening] '/opt/hfs18.0.348/houdini/dso/usd/USD_NC.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/houdini/dso/usd/USD_NC.so' (handle=0x7f07caf9e300)
TfDlopen: [opening] '/opt/hfs18.0.348/dsolib/libpxr_sdf.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/dsolib/libpxr_sdf.so' (handle=0x7f089bf0f970)
TfDlopen: [opening] '/opt/hfs18.0.348/houdini/dso/usd/USD_Plugins.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/houdini/dso/usd/USD_Plugins.so' (handle=0x7f07f35bdd00)
TfDlopen: [opening] '/usr/redshift/redshift4solaris/18.0.348/RSHydra.so' (flag=2)...
TfDlopen: [opened] '/usr/redshift/redshift4solaris/18.0.348/RSHydra.so' (handle=0x7f07caf9de00)
TfDlopen: [opening] '/opt/hfs18.0.348/dsolib/libpxr_glf.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/dsolib/libpxr_glf.so' (handle=0x7f0898730f70)
TfDlopen: [opening] '/opt/hfs18.0.348/dsolib/usd_plugins/hdRpr.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.348/dsolib/usd_plugins/hdRpr.so' (handle=(nil))
TfDlopen: [error on opening] '/opt/hfs18.0.348/dsolib/usd_plugins/hdRpr.so': libRadeonProRender64.so: cannot open shared object file: No such file or directory

**Comment by hshakula** [comment]
Hm, seems like something went wrong on installation - not all files installed, in particular libRadeonProRender64.so.
Could you please try installing again and send me here the output of the installation script?
And what is the output of this command `ls -la /opt/hfs18.0.348/dsolib/libRadeon*`?

**Comment by habernir** [comment]
this is the output 

lrwxrwxrwx 1 habernir habernir      28 Feb 11 10:27 /opt/hfs18.0.348/dsolib/libRadeonImageFilters64.so -> libRadeonImageFilters64.so.1
lrwxrwxrwx 1 habernir habernir      32 Feb 11 10:27 /opt/hfs18.0.348/dsolib/libRadeonImageFilters64.so.1 -> libRadeonImageFilters64.so.1.4.3
-rw-r--r-- 1 habernir habernir 1876600 Dec  6 08:13 /opt/hfs18.0.348/dsolib/libRadeonImageFilters64.so.1.4.3
-rw-r--r-- 1 habernir habernir 2679864 Dec 18 10:34 /opt/hfs18.0.348/dsolib/libRadeonProRender64.so


i install it also for houdini 18.0.287 (its the same result like 18.0.348)

**Comment by hshakula** [comment]
Interesting, what is the output of
`ldd /opt/hfs18.0.348/dsolib/usd_plugins/hdRpr.so | grep Radeon`

**Comment by habernir** [comment]
this is the output

libRadeonProRender64.so => not found
libRadeonImageFilters64.so => not found

**Comment by hshakula** [comment]
As a current workaround, you can set LD_LIBRARY_PATH to /opt/hfs18.0.348/dsolib. In the meantime, I will figure out what's gone wrong.

Just run `export LD_LIBRARY_PATH=/opt/hfs18.0.348/dsolib` in the same terminal window where you ran `export TF_DEBUG...`. After you set LD_LIBRARY_PATH, you can run
`ldd /opt/hfs18.0.348/dsolib/usd_plugins/hdRpr.so | grep Radeon` and make sure that there is no `not found` anymore

**Comment by habernir** [comment]
ok thanks

**Comment by hshakula** [comment]
Hey, I have some updates. Could you please try this [build](https://drive.google.com/file/d/1CszNtem0JPBJ5WTiZmg8mEpnhIGGQ5gC/view?usp=sharing)?
Please run it from the same terminal (with `TF_DEBUG` environment set) as before but unset LD_LIBRARY_PATH (by running `unset LD_LIBRARY_PATH`)

**Comment by habernir** [comment]
[crash.untitled.habernir_22186_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4191950/crash.untitled.habernir_22186_log.txt)
[terminalOUTPUT.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4191951/terminalOUTPUT.txt)

hello 
well its crash after 2 second and i attach the terminal output and also the crash log from houdini log

**Comment by hshakula** [comment]
Good news - it now can find libRadeonProRender64.so.
Bad news - crash. Unfortunately, stack trace in crash log has nothing related to hdRpr. Is it possible to share a project file?

**Comment by hshakula** [comment]
The build I gave had WIP principled shader functionality. Do you have any VOP Principled Shader nodes in your stage?

Anyway, here is the [build](https://drive.google.com/file/d/1PgBXno1zk6JC10xeabuM2HKfvoHtd-4d/view?usp=sharing) of the current master. Could you try this instead?

**Comment by habernir** [comment]
same result.

its always crash, even  with empty scene or with just simple sphere .

perhaps do you know which subject  the houdini crash log file refer to?

and thank you very much for your fast replies

**Comment by hshakula** [comment]
Let me clarify, these two builds I gave you are crashing but the build you downloaded from the release page (that required LD_LIBRARY_PATH to work) is working or it crashes as well?

**Comment by habernir** [comment]
all of them always crash .
even with empty scene or with just simple sphere

**Comment by hshakula** [comment]
Ah, I thought v1.0.0 one worked for you. Okay.
Let's try to get as much info as possible because hdRpr was never tested on Debian 10.
Run these commands:
```
export RPR_ENABLE_TRACING=1
mkdir $HOME/Desktop/rprTrace
export RPR_TRACING_PATH=$HOME/Desktop/rprTrace
export RIF_LOG_LEVEL=4
export HD_RPR_ERROR_OUTPUT_FILE=stderr
export TF_DEBUG="TF_DLOPEN,HD_RPR_DEBUG_CONTEXT_CREATION,HD_RPR_DEBUG_CORE_UNSUPPORTED_ERROR"
```
and run houdini with `houdinifx` from this terminal window

**Comment by habernir** [comment]
i attach the terminal log file
[log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192137/log.txt)

**Comment by hshakula** [comment]
Is there anything in $HOME/Desktop/rprTrace folder?

**Comment by habernir** [comment]
nop.

**Comment by hshakula** [comment]
Ok, I see some suspicious line in the terminal log. Please install this [build](https://drive.google.com/file/d/1rRKZJ_cettNLpoxFsma6ngKw4YL79yJz/view?usp=sharing) and run this as well:
```
export RIF_TRACING_ENABLED=1
mkdir $HOME/Desktop/rifTrace
export RIF_TRACING_PATH=$HOME/Desktop/rifTrace
```

**Comment by habernir** [comment]
this is the ouput from $HOME/Desktop/rifTrace
[rif_trace_1581513078.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192235/rif_trace_1581513078.zip)

and here is the ouput from terminal
[terminalLOG.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192250/terminalLOG.txt)

**Comment by hshakula** [comment]
It did not crash now, right?

**Comment by hshakula** [comment]
And the latest LOG does not seem full, did you run houdini without all previous env variables set?
I mean this
```
export RPR_ENABLE_TRACING=1
mkdir $HOME/Desktop/rprTrace
export RPR_TRACING_PATH=$HOME/Desktop/rprTrace
export RIF_LOG_LEVEL=4
export HD_RPR_ERROR_OUTPUT_FILE=stderr
export TF_DEBUG="TF_DLOPEN,HD_RPR_DEBUG_CONTEXT_CREATION,HD_RPR_DEBUG_CORE_UNSUPPORTED_ERROR"
```

**Comment by habernir** [comment]
this is the ouput from $HOME/Desktop/rifTrace
[rif_trace_1581514383.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192547/rif_trace_1581514383.zip)

and here is the ouput from terminal
[terminalLOG.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192549/terminalLOG.txt)

rprTrace folder is empty

**Comment by habernir** [comment]
and i can see the percents going up but it crash after a few seconds

**Comment by hshakula** [comment]
Please send me `/tmp/houdini_temp/crash.untitled.habernir_5682_log.txt` also

**Comment by habernir** [comment]
here it is
[crash.untitled.habernir_5682_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4192571/crash.untitled.habernir_5682_log.txt)

**Comment by hshakula** [comment]
I've started debugging. I will write to you here when I will have something

**Comment by hshakula** [comment]
Hi @habernir, could you please send me the output of `clinfo` command?

**Comment by hshakula** [comment]
And what's your effective viewport resolution? Do you use a 4K display? If yes, do you stretch Houdini to full screen when you are testing?
I just want to eliminate memory issues here

**Comment by habernir** [comment]
i have 3440*1440 display resolution

and  i work in full screen with houdini.

and here is the output of clinfo
[openclLOG.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4198581/openclLOG.txt)

**Comment by hshakula** [comment]
Could you please try running RPR with a really small viewport? Just to make sure

**Comment by habernir** [comment]
the same

**Comment by hshakula** [comment]
Can I see the terminal output as yesterday? So that I can make sure that the crash has the same symptoms

**Comment by habernir** [comment]
ok but i will do it later or tomorow because i need to go.

**Comment by habernir** [comment]
here is the ouput files
[rif_trace_1581620902.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4200498/rif_trace_1581620902.zip)
[crash.untitled.habernir_5546_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4200500/crash.untitled.habernir_5546_log.txt)
[terminalLOG.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/4200504/terminalLOG.txt)

**Comment by hshakula** [comment]
Hey, @habernir, I wonder if you had the opportunity to test the latest release?

**Comment by bsavery** [comment]
Closing, reopen if still observed with latest.
