### ISSUE TITLE
Build instructions say you need ProRender SDK v1.34.7, but that's not currently available.

### ISSUE THREAD

**Issue by ringdk** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#248]
Build instructions say you need ProRender SDK v1.34.7, however as of writing this the publicly available version is v1.34.2.

Possibly due to this I'm seeing a lot of build failures where constants such as 'RPR_MATERIAL_INPUT_UBER_DIFFUSE_WEIGHT' are not defined anywhere.

**Comment by bsavery** [comment]
The latest sdk is available here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK now.  We are moving to use git submodule to make this easier.
