### ISSUE TITLE
Viewport is empty when i use RPR

### ISSUE THREAD

**Issue by LollEdo** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#259]
![Annotazione 2020-03-16 214910](https://user-images.githubusercontent.com/62264464/76798541-0ef4bc80-67d0-11ea-92dd-97dd1104df16.png)
The render is obv total black.
Sorry if the answer is too easy.

**Comment by hshakula** [comment]
Hi, no worries, is it possible to share .hip or send it to my email swrqmail@gmail.com?

**Comment by LollEdo** [comment]
GitHub does not support this file, i will send it by email. Thank you

**Comment by hshakula** [comment]
That's how it looks for me
![Balls](https://user-images.githubusercontent.com/22181845/76849225-af3cf680-684d-11ea-898f-e61485c43bd0.png)

Let's figure out what's going on.
Please set environment variable TF_DEBUG to
"TF_PRINT_ALL_POSTED_ERRORR_TO_STDERR TF_DLOPEN HD_RPR_DEBUG_CONTEXT_CREATION HD_RPR_DEBUG_CORE_UNSUPPORTED_ERROR" (without quotes) and run Houdini. Here's more or less reasonable [instruction](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) how to do it.

**Comment by bsavery** [comment]
Hi @LollEdo  Please reopen if this is still an issue.
