### ISSUE TITLE
19.07 renders red in macOS

### ISSUE THREAD

**Issue by bsavery** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#26]
AOV issue?

**Comment by hshakula** [comment]
I finally managed to reproduce it on macOS, but only by intentionally failing rpr context creation.
Could you please provide debug output?

My setup:
- Hardware: iMac 2017 with Radeon Pro 570
- OS: 10.14.5

**Comment by hshakula** [comment]
Is the issue still reproducing?
