### ISSUE TITLE
What's the text string for Houdini.env?

### ISSUE THREAD

**Issue by dgasen** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#278]
Hello. I managed to install RadeonProRender for Houdini by using python3 install.py earlier today.

However. I need to string for the Houdini.env file in order to open the renderer inside houdini.

I could not find any information about this text string in the downloaded package.

Would anyone be kind and tell me what to put in the houdini.env file.
Thanks.

**Comment by hshakula** [comment]
Hi, have you tried opening LOP viewport and you don't see RPR in the list of renderers?
Currently, hdRpr is installing inside of Houdini and so you don't have to add any paths in Houdini.env

**Comment by dgasen** [comment]
Hello, and thanks for quick answer!
I have installed both houdini 18.0.287 and 18.0.416. And both gives the same result.
When i type rpr inside an lop network, i get to see the rpr properties node. But it shows that it is  missing some dependencys? 

I hope any of my printscreens can provide any closuer.
/Erik

![Screenshot from 2020-05-03 19-48-53](https://user-images.githubusercontent.com/34615610/80922246-0fdfae80-8d7c-11ea-8284-93e7bfef8e69.png)
![Screenshot from 2020-05-03 19-50-18](https://user-images.githubusercontent.com/34615610/80922250-13733580-8d7c-11ea-98d7-3ebd1da5960b.png)

**Comment by hshakula** [comment]
You are doing it wrong.

The graph is for describing the stage.

To select the renderer use "persp" button
![80922246-0fdfae80-8d7c-11ea-8284-93e7bfef8e69](https://user-images.githubusercontent.com/22181845/80922318-ef682200-8d84-11ea-8eea-59257af63113.png)

I can advise you to follow at least this tutorial https://www.sidefx.com/docs/houdini/solaris/tutorials.html
It should give you some insights

As a quick test add "Sphere" to the stage and select RPR. What do you see?

**Comment by dgasen** [comment]
Ok. I have added a sphere in a lop network and switched to 'RPR Perspective'.

![Screenshot from 2020-05-03 20-35-48](https://user-images.githubusercontent.com/34615610/80922494-d4de7a80-8d7d-11ea-910a-f88a1f9f05f6.png)

**Comment by dgasen** [comment]
Iguess i have it installed then. Would you have any more documentation on amd radeon pro render in houdini? Where can i find the render node etc, Where can i find the Radeon pro render materials etc. Thanks /Erik

**Comment by hshakula** [comment]
Unfortunately, there is no documentation yet.
But I can straightforwardly tell you that you can use (almost) every available node except, of course, nodes with "Karma" in its name.

Supported materials: "USD Preview Surface" and "Principled shader" (without VEX)

Render node is "USD Render ROP". This node is not bound to a particular renderer.

So theoretically you should be able to follow any tutorial about the LOP pipeline and it should work for RPR. If you find something that contradicts with my words, feel free to post another issue, it will be discussed separately

**Comment by dgasen** [comment]
Alright. Thanks alot!

**Comment by bsavery** [comment]
Thanks!  We'll work on documentation soon.
