### ISSUE TITLE
missing shader nodes

### ISSUE THREAD

**Issue by sanderlipmann** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#304]
Hi all,

Just installed prorender for houdini and looks like most stuff is working but I seem te be missing the shaders in materials. 

These:
![image](https://user-images.githubusercontent.com/68067767/87048403-f59ed280-c1fb-11ea-83f2-2fbcabbf339c.png)

Look, missing:
![image](https://user-images.githubusercontent.com/68067767/87048837-85dd1780-c1fc-11ea-9478-103ae98758de.png)

Any ideas to activate them?

Thanks in advance, Szann

**Comment by hshakula** [comment]
Where did you download the package? On the "release" page?

**Comment by hshakula** [comment]
The feature you are looking for is not even merged into the develop branch. I will make you a build.

Replace the content of your active package with this [package](https://drive.google.com/file/d/1SWvn33PRIBBNIONmopbeEOYgPvAXNSKZ/view?usp=sharing).

**Comment by sanderlipmann** [comment]
I first downloaded 1.2.2 from the release page and after troubleshooting downloaded 1.2.7 a direct link from google drive page. Both had the same issue.

**Comment by hshakula** [comment]
Hm, let me know if the build I just sent does not work either.

**Comment by sanderlipmann** [comment]
Oh haha I did not realize that. I was looking for AOV's and came across that picture and figured that was a pretty important part that was missing. Going to try your build. Thanks in advance.

**Comment by hshakula** [comment]
Hello, any news?
