### ISSUE TITLE
RPR option desapears after first attempt

### ISSUE THREAD

**Issue by martinlarravide** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#306]
HI. I fallow the instructions for install (houdini 18.0.460 on Ubuntu 20.04, radeon vii, threadripper 1950x) , and when I open stage, i add and object, change the viewer to RPR turns to storm, and rpr option desapears. Any help please?

**Comment by hshakula** [comment]
Hi, usually it happens when houdini fails to load plugin library. Follow instructions from this [message](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/230#issuecomment-581445665) to get more info about library loading process

**Comment by martinlarravide** [comment]
well, thank you
i fallow what you said and i get this error


TfDlopen: [opened] '/opt/hfs18.0.460/houdini/dso/usd/USD_Plugins.so'
(handle=0x7f8a7d4bb400)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/libpxr_usd.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/libpxr_usd.so'
(handle=0x7f8b14e08f70)
TfDlopen: [opening] '/opt/hfs18.0.460/houdini/dso/usd/USD_NC.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/houdini/dso/usd/USD_NC.so'
(handle=0x7f8a7d2a3400)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/libpxr_sdf.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/libpxr_sdf.so'
(handle=0x7f8b14e09990)
TfDlopen: [opening] '/opt/hfs18.0.460/houdini/dso/usd/USD_Plugins.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/houdini/dso/usd/USD_Plugins.so'
(handle=0x7f8a7d4bb400)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/usd_plugins/hdStorm.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/usd_plugins/hdStorm.so'
(handle=0x7f8a7d2a2f00)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/libpxr_glf.so' (flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/libpxr_glf.so'
(handle=0x7f8b1162af80)
TfDlopen: [opening] '/opt/hfs18.0.460/houdini/dso/usd/USD_Plugins.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/houdini/dso/usd/USD_Plugins.so'
(handle=0x7f8a7d4bb400)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/libpxr_usdImaging.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/libpxr_usdImaging.so'
(handle=0x7f8b0f743000)
TfDlopen: [opening] '/opt/hfs18.0.460/houdini/dso/usd/BRAY_HdKarma.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/houdini/dso/usd/BRAY_HdKarma.so'
(handle=0x7f8a60192200)
TfDlopen: [opening] '/opt/hfs18.0.460/dsolib/usd_plugins/hdRpr.so'
(flag=2)...
TfDlopen: [opened] '/opt/hfs18.0.460/dsolib/usd_plugins/hdRpr.so'
(handle=(nil))
TfDlopen: [error on opening]
'/opt/hfs18.0.460/dsolib/usd_plugins/hdRpr.so': libOpenGL.so.0: cannot open
shared object file: No such file or directory


thats help? what do I need to do? thats a library that I need to install?
thank you very much

martin

**Comment by hshakula** [comment]
Yeah, try this “sudo apt install libopengl0 -y”

**Comment by martinlarravide** [comment]
now I get this

TfDlopen: [error on opening]
'/opt/hfs18.0.460/dsolib/usd_plugins/hdRpr.so': libGLX_nvidia.so.0: cannot
open shared object file: No such file or directory

**Comment by hshakula** [comment]
Hm, plugin should not have any direct linkage to OpenGL at all, I will fix it.

In the meantime, please, try this build https://drive.google.com/file/d/116aVlxCu0VLOaT4JdgkGvxlZruPOgbXA/view?usp=sharing

**Comment by martinlarravide** [comment]
well, thats is working, It is fast.
Do you know were I can find any manual or something for this prorender in
houdini? I dont know how to export an image.
Thank you very much.
Martin.

**Comment by hshakula** [comment]
We don’t have any public documentation yet but in general everything (almost) that works in karma should work in RPR. If you find anything in contrary with this statement, feel free to create a new issue.

See sidefx official documentation about image exporting - https://www.sidefx.com/docs/houdini/nodes/out/usdrender.html

**Comment by hshakula** [comment]
> Hm, plugin should not have any direct linkage to OpenGL at all, I will fix it.

It's already fixed in the latest develop, so next release will not have such an issue
