### ISSUE TITLE
RPR material causes segmentation fault error/crash

### ISSUE THREAD

**Issue by katohmy** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#356]
I seem to be having trouble assigning RPR materials in the material network.  I keep getting a segmentation fault error that leads to a crash when I assign an RPR material to an object or even just trying to add a RPR material node to a new .hip file.  What am I missing/doing wrong?  I've attached my last crash log to this issue.  Thanks in advance,

![Capture](https://user-images.githubusercontent.com/72123807/94651363-52a9b080-0333-11eb-8633-369ff9c8c401.JPG)

[crash.untitled.Katohmy_12004_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5303562/crash.untitled.Katohmy_12004_log.txt)

**Comment by hshakula** [comment]
What RPR build do you use? How did you install it - with help of Houdini’s package system or copied build directly into the Houdini tree?

**Comment by katohmy** [comment]
Using the most recent build (1.3.2) and installed following the automatic process (activateHoudiniPlugin python installation).  The python window closed as soon as it opened, but once I opened Houdini and switched to the stage network, RPR perspective was available.

**Comment by hshakula** [comment]
I just tried 1.3.0 release build (hdRpr-1.3.2-Houdini-18.0.532-Windows.tar.gz) with Houdini 18.0.584 (18.0.566 production) and I can reproduce the crash. But if I recompile the plugin against the target Houdini, it works. So most likely SideFX made some breaking changes in their ABI. We will update the builds for the newer Houdini. 

In the meantime, please try this [build](https://drive.google.com/file/d/1BY3PpBc_k8Iyyv-v40Lof8SGxTa_xsAA/view?usp=sharing).

**Comment by katohmy** [comment]
Really appreciate the swiftness, many many thanks.  

Forgive me for being a noob, but what's a good way to go about uninstalling the current RPR build so as to avoid running into this problem again?  Or will this new build overwrite the last one?

**Comment by hshakula** [comment]
If you are always using automatic activation then you can just call activate on new build and it should be ok already. And ofc you can just delete the old package. We are not installing anything to the system folders except package JSON in Houdini preference dir that is overwritten by the activation script

**Comment by katohmy** [comment]
Got it up and running.  Material nodes load just fine without issue.  Thanks again.
