### ISSUE TITLE
importing VDBs into LOP network issue

### ISSUE THREAD

**Issue by katohmy** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#363]
Hello again, I have another bit of an issue.
Stuttering and crashing occurs when multiple VDBs are inserted into a LOP network nodes via SOP import or SOP create when setting up stage for rpr export.  It may be a data issue, but there is no crash log for when this occurs.

Is there a solution to this outside of the lop network?  Or is my data simply too large?

**Comment by hshakula** [comment]
Shin gave me your data. I've recreated your LOP graph and reproduced the crash. I have a fix for the crash.

After applying the fix I can import all volumes. But I see other problems with your setup. You have a few overlapping volumes. RPR does not work correctly for such a setup, at least that's how it is in RPR1.0 (Tahoe), volumes RPR 2.0 does not support volumes yet.

Here is what I'm saying about:

* grain_pyro_rndr only

![grain_pyro_rndr](https://user-images.githubusercontent.com/22181845/95583451-d276ff80-0a44-11eb-8f6f-e0b1a7f98615.png)

* snow_grain_rndr only

![snow_grain_rndr](https://user-images.githubusercontent.com/22181845/95583500-e3c00c00-0a44-11eb-9b02-c2cb4435dec2.png)

* grain_pyro_rndr + snow_grain_rndr

![grain_pyro_rndr_with_snow_grain_rndr](https://user-images.githubusercontent.com/22181845/95583517-ec184700-0a44-11eb-8efc-9f4e17088148.png)

* grain_pyro_rndr + snow_grain_rndr (y position + 0.25)

![grain_pyro_rndr_with_snow_grain_rndr_+0 25y](https://user-images.githubusercontent.com/22181845/95583642-1c5fe580-0a45-11eb-9a5a-9e007a0b18de.png)

**Comment by katohmy** [comment]
Thanks for the finding a solution to the issue so swiftly.  Is there a build I can download with the fix?

I understand the situation regarding overlapping volumes.  I don't suppose there is a plan for implementing a solution for that or when RPR 2.0 will allow volumes?

**Comment by hshakula** [comment]
Let me know your Houdini version and platform, I will create a build.

I’m pretty sure the overlapping volumes problem will not be fixed in the Full render quality but I know that overlapping volumes will work in RPR 2.0 (I saw a working prototype). But I don’t know when volumes will be enabled, Shin should I know more about it

**Comment by katohmy** [comment]
Currently using Houdini 18.0.566.
Thanks again.

Quick side question: Is there a way to increase the voxel quality of the volumes in RPR?  Would a VDB resample node in the initial geometry solve this?

**Comment by hshakula** [comment]
You didn't specify your platform.

As far as I know, RPR does not interpolate volume data when tracing it, this leads to such a blocky appearance. I’m not sure that the resample node will do the thing, but all you need is to increase resolution and apply some filter (with quite a small kernel size) to smooth data

**Comment by katohmy** [comment]
Sorry about that.  Platform is Windows.

**Comment by hshakula** [comment]
https://drive.google.com/file/d/124uXAyRxju___2ltdcXIEuSg4II-j-QN/view?usp=drivesdk

**Comment by katohmy** [comment]
Got it.  Thanks so much.
Last stupid question, just want to confirm:  As you mentioned increasing resolution, the render settings node in the stage network should go underneath the rpr export, correct?

**Comment by hshakula** [comment]
RPR export is quite a specific node, so it does not matter actually

**Comment by katohmy** [comment]
New build worked like a charm.  No more crashes in the lop network.  Thanks again.

Also, one last thing I just have to know cause I can't figure it out.
How did you get an alpha output for the background.  I've been trying everything and I can't seem to get it export out as anything other than a white background due to the lighting.

**Comment by hshakula** [comment]
Hm, it should have been enabled by default. There is special boolean in render settings - “enable alpha” or something like that, I can’t check exactly right now. Try to check/uncheck it, do you see any difference?

**Comment by hshakula** [comment]
Maybe you encounter some errors, Houdini hides them by default. Please set environment variable TF_DEBUG to
"TF_PRINT_ALL_POSTED_ERRORR_TO_STDERR" (without quotes) and run Houdini. We will see if you have any errors

**Comment by katohmy** [comment]
Will do, I'll give that a go.
I'll also take a look at my render settings again.  I'm also under the impression I've been rendering things out differently this entire time.  I've always just been exporting from the rpr export node.

**Comment by katohmy** [comment]
So, did everything and no errors.  I think something happened when you fixed the vdb issue?

Now even my earlier setups where I easily could output an alpha come up as grey despite no background or lights.  And of course, I've set the display options to black and set enable color alpha.

**Comment by hshakula** [comment]
I gave you the latest develop branch build. So most likely some other changes broke it for you. The worst part of it that I can’t reproduce it. What’s your hardware and what hdRpr version you were using before?

**Comment by katohmy** [comment]
Shoot.  I appreciate your efforts though.  Here are my hardware specs.

CPU: AMD Ryzen 5 1600X 6-Core 3.60 GHz
RAM: 32 GB
GPU: NVIDIA GeForce RTX 2070
Last hdRpr version: 1.3.2-Houdini-18.0.566-Windows

**Comment by katohmy** [comment]
Sorry for being a bother.  Any ideas as to how to solve this?
![snowing](https://user-images.githubusercontent.com/72123807/95966563-400c9c80-0e46-11eb-8cbe-4fc30d1a9fbc.png)
![snowfall_normal_0001](https://user-images.githubusercontent.com/72123807/95966562-3edb6f80-0e46-11eb-8aae-d9c07ab764a5.jpg)
The left is my houdini window and the right is my render.  I've tried on another machine as well, and it's still the same issue.

**Comment by hshakula** [comment]
How did you get the “render”? Husk?

Houdini window is something you expect to see (black background disturbs me)?

**Comment by hshakula** [comment]
> Shoot. I appreciate your efforts though. Here are my hardware specs.
> 
> CPU: AMD Ryzen 5 1600X 6-Core 3.60 GHz
> RAM: 32 GB
> GPU: NVIDIA GeForce RTX 2070
> Last hdRpr version: 1.3.2-Houdini-18.0.566-Windows

I have a machine with the pretty same configuration but I can't access it right now, I will have access on the next week

**Comment by katohmy** [comment]
No, not from Husk.  I'm exporting from the .rpr export node and rendering from a render farm (it's my company's way of doing things).
It's supposed to be a snowfall particle field with no background so it can be composited in later.  Sorry, didn't mean to disturb you. (O_O)

**Comment by hshakula** [comment]
You are not disturbing me, I decide on my own when I want to see GitHub notifications, so feel free to post messages/issues whenever you want.

If you will disable color alpha in render settings you should see the same image in houdini as you get from render farm.

As I see what happens, you have no lights on the scene and so plugin adds implicit environment light with flat grey color, this light is obviously exported to .rpr. I have no experience with RPR render farm but seems like it does not combine color and opacity AOVs (as we do in the plugin when color alpha is enabled).

**Comment by katohmy** [comment]
Thanks again for all of the support, though.

I definitely enabled color alpha in the render settings.  I assure you.  
I also do have light in the scene (a dome light and a regular light in the node tree), but is it isn't registering in the export now?
Usually it does.  The last build of hdRpr (the one before the vdb fix) rendered it out just fine without the flat grey background.

You think it's the render farm?  Could it be the rpr export node itself?  
I would really like to know what your workflow is if you have another way.

**Comment by hshakula** [comment]
Hm, something weird is going on then. I would prefer to postpone this issue until I have access to the machine I was talking about. Ok?

And it would be nice if you can share this hip, let me know if you cannot share it here I will give you my email.

I cannot say right now anything about workflow for render farm, I was not using it before, I will contact Shin or Takahiro about access to render farm and try it myself

**Comment by katohmy** [comment]
Got it.  Much appreciated and yeah, we can get back to it next week when you are near your machine.
Since it's the studio's file, I definitely can't pass it along here, so if you could give your mail, that would be awesome.  

Thanks again.

**Comment by hshakula** [comment]
swrqmail at gmail.com
