### ISSUE TITLE
.hip files saved in RPR viewport can't be reopened without crash

### ISSUE THREAD

**Issue by katohmy** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#367]
Houdini version: 18.0.566
hdRpr version: 1.3.16-Houdini-18.0.566-Windows

I personally haven't experienced this, but a client has had this issue from yesterday.
When saving the scene with selecting RPR as viewport renderer and opening its scene again, Houdini crashes with high probability.

**Comment by hshakula** [comment]
Hi, do you have a crash report from Houdini or does it crash without saving one?
Could you please upload one of the .hip files that crash? Or send it to my email.

**Comment by katohmy** [comment]
Hey there,
I don't have the file on hand myself, a studio has it, so I will ask for the details on Wednesday.  I'll send you the files if necessary.
