### ISSUE TITLE
Houdini 18.5 - can't switch to render pro option & disappears from menu 

### ISSUE THREAD

**Issue by Kurt-Nielsen** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#376]
I followed setup instruction from https://www.youtube.com/watch?v=bwv2N2i3lTk&t=506s
Maybe things are different since then. I am running an RTX 2080Ti but I was informed that it would work with any GPU.

**Comment by BrundleThwaite** [comment]
I have the same problem. Added to this The RPR menu also no longer shows up when using material library.

You can render but as soon has you have switched to another renderer you cannot switch back.

**Comment by hshakula** [comment]
You all are trying a plugin that was built for 18.0 in Houdini18.5? Check the plugin package name.

If you have no capacity to build the plugin by yourself (that’s easy if you have visual studio installed) then you will need to wait until we push the plugin compiled specifically for Houdini18.5

**Comment by superdude12399** [comment]
How to compile for 18.5 for windows?

**Comment by hshakula** [comment]
@superdude12399

1. Install Visual Studio 2017 and CMake
2. Clone or download the RadeonProRenderUSD
3. Open `Command Line Tools (your Houdini version)` and change directory to the root of RadeonProRenderUSD
4. Run the following commands:
    * `mkdir build`
    * `cd build`
    * `cmake -DCMAKE_INSTALL_PREFIX=_package -G "Visual Studio 15 2017 Win64" ..`
    * `cmake --build . --target install --config Release`

@ascensionseries, @BrundleThwaite in case you need a build for windows - here I compiled the latest develop branch https://drive.google.com/file/d/1IOVnQWSWN1dhJbzDy57eKdVkKRMTnrf7/view?usp=sharing. To understand how it differs from the latest release see [this](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/compare/develop)

**Comment by BrundleThwaite** [comment]
@hshakula 

Thanks for taking the time the build a new version (Especially as it is the weekend).

**Comment by superdude12399** [comment]
@hshakula Thanks!

How do you add materials to an object in the solaris scene for RPR? Are there any example hip files that I can have a look at to learn from? Thank you

**Comment by Kurt-Nielsen** [comment]
> You all are trying a plugin that was built for 18.0 in Houdini18.5? Check the plugin package name.
> 
> If you have no capacity to build the plugin by yourself (that’s easy if you have visual studio installed) then you will need to wait until we push the plugin compiled specifically for Houdini18.5
> 
> @ascensionseries, @BrundleThwaite
> For what platform do you need a plugin?

Windows -thanks hshakula

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/releases/tag/v1.3.22

**Comment by bsavery** [comment]
Updated builds for 18.5

**Comment by hshakula** [comment]
@superdude12399, in the same way as you would do it for Karma.

1. Add `Material Library` LOP node.
2. Set up some material graph. RPR supports:
    * RPR VOP nodes 
        ![image](https://user-images.githubusercontent.com/22181845/97203369-5fe47e80-17bd-11eb-96ec-b770d5fdf764.png)
    * USD VOP nodes
        ![image](https://user-images.githubusercontent.com/22181845/97203609-b9e54400-17bd-11eb-8167-5c508d1f7f7e.png)
3. Attach this material to something
    ![image](https://user-images.githubusercontent.com/22181845/97203846-0761b100-17be-11eb-987f-cfc8ead1d8ef.png)

.hip file: [materialSample.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5440261/materialSample.zip)

My advice would be to go through these [tutorials](https://www.sidefx.com/tutorials/3rd-party-rendering-in-solaris/) with either Karma or RPR. After that, you should understand most of the things you need to proficiently use Solaris

**Comment by U-se** [comment]
Thank you for updating this for H18.5 so quickly. I have used the installer activateHoudiniPlugin.exe and it correctly placed a .jason file into the 18.5 packages. Unfortunately, Houdini 18.5 won't start with that .jason file. This is the error I receive:
![2020-10-27 11_20_08-Deadline Monitor  -  C__DeadlineRepository10](https://user-images.githubusercontent.com/73528254/97288670-784cab80-1846-11eb-93d7-3b5add387ab1.jpg)

I do have two Houdini versions installed as I need H18 for projects I am currently working on, but I do not have changed anything in my System environment variables.  I have tried to look at the SideFXLabs .jason file but I can't figure out what to change in the RPR .jason file to properly recognize H18.5

Thank you all!

**Comment by hshakula** [comment]
It's the issue of this exact daily build - https://www.sidefx.com/forum/topic/76257/

You can try applying the fixes listed in this topic for RPR to work with Houdini 18.5.375

**Comment by U-se** [comment]
> It's the issue of this exact daily build - https://www.sidefx.com/forum/topic/76257/
> 
> You can try applying the fixes listed in this topic for RPR to work with Houdini 18.5.375

Thank you that was it. Updated to the Daily build 18.5.378 and it's working fine. Sorry, I should've thought further than blaming RPR for this!

**Comment by superdude12399** [comment]
@hshakula Thanks! Is there a materials library for RPR Houdini similar to that of Blender?

**Comment by hshakula** [comment]
@superdude12399, unfortunately, the material library is not integrated with the RPR Houdini plugin.

But soon we will release RPR plugin with MaterialX support and hopefully convert the current material library to MaterialX. It will greatly simplify work with materials.

P.S. mtlx support is actually mostly done, if you want I can send you a build, it would be nice to get any feedback

**Comment by superdude12399** [comment]
@hshakula I would love to try out the build, download link pls, thanks!

**Comment by hshakula** [comment]
@superdude12399, https://drive.google.com/file/d/1INWJNJV60mGN9EA1OUjJ0fSZA-izcEbF/view?usp=sharing

**Comment by BrundleThwaite** [comment]
When you  have then next official release will you have builds for the python 3 version of Houdini 18.5 as well as the default release. 

I have compiled a python 3 version so I do not need a build but it would probably be a good idea to  support both versions.

**Comment by hshakula** [comment]
@BrundleThwaite, most likely yes
