### ISSUE TITLE
Rpr disappears when selected. Rep - 1.3.22 Mac OS Houdini 18.5

### ISSUE THREAD

**Issue by shamilion** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#384]
When RPR is selected in the viewport, the rpr is no longer displayed. Installed RPR by running
ActivateHoudiniPlugin.
Mac OS Catalina 
Houdini 18.5

**Comment by orkoid** [comment]
If you rely on pro render, you can try to build it yourself, or fall back to houdini 18.0

**Comment by hshakula** [comment]
I'm already checking, hang on

**Comment by wongdi** [comment]
> > 如果你依靠专业渲染， 你可以尝试自己构建它， 或回到胡迪尼 18.0
> 
> 不幸的是， 在 Mac Os 上， 我不知道如何构建:(如果有人帮忙， 我会很高兴的。

I will not build it, but this does not affect my learning of Solaris. Can only wait for fix. @hshakula

**Comment by hshakula** [comment]
I've found the problem, I will upload a build with a fix when it's ready.

**Comment by Redcroft** [comment]
Also having this issue under linux (fedora and ubuntu), cheers

**Comment by hshakula** [comment]
> Also having this issue under linux (fedora and ubuntu), cheers

Yeah, this issue is uniform across UNIX systems

**Comment by hshakula** [comment]
[macos build](https://drive.google.com/file/d/1m2lmE2RM-hQVSrbaaSiO7uTZEgXKiMzH/view?usp=sharing)

**Comment by wongdi** [comment]
> [macos build](https://drive.google.com/file/d/1m2lmE2RM-hQVSrbaaSiO7uTZEgXKiMzH/view?usp=sharing)

Does the repair of the Windows build take some time?  same question。

**Comment by hshakula** [comment]
@wongdi Hm, I didn’t know that windows build does not work. Could you please create a separate issue for this with a description of the issue and the used build?
