### ISSUE TITLE
Windows build does not work with houdini 18.5

### ISSUE THREAD

**Issue by wongdi** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#387]
Windows 2004 19041.572
Houdini 18.5.351 py3

same question。

[屏幕录制.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5461765/default.zip)

**Comment by hshakula** [comment]
Py3 version requires a different plugin build because it ships with different USD libraries that are used by the plugin. We did not yet set up automatic builds with py3 Houdini and I don't know when we will do it.

For your convenience I would advise you to get hands-on building the plugin on your own. But of course, if you need it ASAP, I can do it for you. Let me know

And could you please specify in the name of the issue that we are talking about Houdini 18.5 Py3?

**Comment by wongdi** [comment]
> Py3 version requires a different plugin build because it ships with different USD libraries that are used by the plugin. We did not yet set up automatic builds with py3 Houdini and I don't know when we will do it.
> 
> For your convenience I would advise you to get hands-on building the plugin on your own. But of course, if you need it ASAP, I can do it for you. Let me know
> 
> And could you please specify in the name of the issue that we are talking about Houdini 18.5 Py3?

I don't have the ability to build it, and I can't describe the others, I just selected the PBR preview in the view, and then it disappeared, nothing more. If an error report is generated, I can upload it to you. The premise is that you tell me where it is. I can go back to the traditional version and use it. I am a student and do not rely on it for production. So i can wait for the new build to adapt to py3. I still suggest to declare it in README.md so that others can understand this issue.

ps:I think you can provide a py3 version when you have time.😊

**Comment by hshakula** [comment]
> I just selected the RPR preview in the view, and then it disappeared

That's typical behavior when libraries failed to load. You can make sure that you are experiencing this problem by setting `TF_DEBUG=TF_DLOPEN` environment variable, USD will start logging the dynamic library loading process.

I will make you a build, for now, but do not expect that we will post py3 builds all the time, until ofc, it will become the default Houdini build.

**Comment by hshakula** [comment]
[py3 build](https://drive.google.com/file/d/1FJQHSsPscpauYfOM22diYFUXEjmclYIf/view?usp=sharing)

**Comment by wongdi** [comment]
> I will make you a build, for now, but do not expect that we will post py3 builds all the time, until ofc, it will become the default Houdini build.
 ok thanks for your build.there are no new features released for houdini, I will stay here. after all, for me, I only use it to learn.😉

ps:Google translation may not be able to express it completely。
