### ISSUE TITLE
Volume/VDB Shader

### ISSUE THREAD

**Issue by U-se** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#389]
Hello,

I have been testing RPR more and more and have tried to make a comparison between Karma and RPR in terms of Volumes. Converting my Pyro sim to VDB and importing it into LOPS works great and RPR does render it, it even seems to understand the temperature field. 
Unfortunately, I wasn't able to get the RPR Volume Shader to work (or do any other modification like increasing density or changing colors with the Shaders).
And it seems like only the dome light has any effect on the VDB.

Could it be that this isn't implemented yet?
Besides that, I really like how fast it stays even with big(ish) volumes.
I have attached a modified scene file with a single frame of the volume in case this will help you in any way:
https://drive.google.com/file/d/1U4mr5ohcJDE1nS9vF8ZTqNGE3qZtG7B-/view?usp=sharing

(It's somewhat big due to the volume so if somebody will read this in a month or so I probably deleted it from my drive)

Edit: Added a Screenshot for more clarity
![2020-11-01 14_19_32-](https://user-images.githubusercontent.com/73528254/97804007-5c357980-1c4d-11eb-96af-eee08d831d50.jpg)

**Comment by hshakula** [comment]
Hi, @U-se, I wonder have you seen my recent message on RPR's discord about volumes?
https://discord.com/channels/374991700625719306/629830290575065098/771060408999346188

**Comment by U-se** [comment]
I hadn't seen that. Thank you for pointing me to Discord. The example file you provided was very insightful!

**Comment by petermandk** [comment]
I would also love to know, how to properly shade volumes, could I get the access to discord please?
