### ISSUE TITLE
Displacement Texture

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#399]
Hi,

I'm not sure if this is an issue or if I'm just using the wrong workflow but I have a displacement texture that I am using that works fine with Karma but when I switch to RPR then all displacement goes away. I've tried several different shader setups from using the principled to using the RPR combine with an RPR uber and a displace texture and output node and I can't seem to figure out how to get texture displacement working, am I just going about this wrong? Thanks in advance

**Comment by hshakula** [comment]
Hi, can you share a sample hip?

**Comment by AlxndrTheWretch** [comment]
Yes, here is two ways I tried to accomplish it (the one setup obviously doesn't work in Karma as it uses RPR nodes)
[Displacement.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5562633/Displacement.zip)

**Comment by hshakula** [comment]
* rubber_toy material does not work because Houdini sets the displacement terminal only for karma:
    ![image](https://user-images.githubusercontent.com/22181845/99665462-51168200-2a72-11eb-858f-e6587982fba1.png)
    (as you can see outputs:displacement does not have any bound node)

* pighead material does not work because you are using VEX based node (RPR just can't work with it):
    ![image](https://user-images.githubusercontent.com/22181845/99665792-c6825280-2a72-11eb-8465-5e4dcc98516a.png)

I've updated rubber_toy material, please check [Displacement.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5566784/Displacement.zip)

**Comment by AlxndrTheWretch** [comment]
Thank you, that helps a lot. I figured it was something about how I was setting it up but I couldn't find answers for it anywhere

**Comment by hshakula** [comment]
Have you seen this tut https://www.sidefx.com/tutorials/3rd-party-rendering-in-solaris/? Varo explained such things quite well

**Comment by AlxndrTheWretch** [comment]
No I haven't, thank you!
