### ISSUE TITLE
Sphere light shape 50% smaller than in Maya

### ISSUE THREAD

**Issue by radon199** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#4]
Hey,

Really great to try out ProRender. I downloaded the pre-compiled version for windows and USD 0.8.5

I noticed that using a sphere light I need to double the visual size in Maya in order for it to show matching the sphere in Rpr in USDView.

Because the default hdStream renderer has no visual representation of lights yet, it's hard to tell exactly where the problem comes from. Could be USD or ProRender.

When creating a PxrSphereLight in Maya it will appear 50% smaller than a default Maya sphere. Scaling the pxr light to match the Maya sphere visually will result in it rendering 50% smaller in ProRender. In order to make it match in USDView I needed to double the size of the PxrSphereLight.

![usdview](https://user-images.githubusercontent.com/39324245/44942581-b7b40600-ad69-11e8-946a-8c19412f14ae.jpg)

![maya](https://user-images.githubusercontent.com/39324245/44942582-bc78ba00-ad69-11e8-8f0b-d17acd4a4ece.jpg)

**Comment by bsavery** [comment]
Hmmm, that's interesting.  Can you attach the USD file, just for quickness of fixing?

**Comment by radon199** [comment]
Hi Brian,

I decided to change the example a little.

For the below screenshot from USDView and usd file, both the polySphere and the pxrSphereLight are the same size visually in both the Maya viewport and a Renderman21.0 render.

By default a pxrSphereLight has a diameter of 1 unit ( 1unit=1cm ) in Maya, but the sphere has a diameter of 2 units ( or a radius of 1 unit ) and so the scale of the light is set to 2 so that they match.

Despite this, in USDView and ProRender I am seeing the light as 50% smaller than the polySphere.

![spherelightscale](https://user-images.githubusercontent.com/39324245/44991934-9e1de480-af4a-11e8-83cd-00a6982388c7.jpg)

[lightTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/2345871/lightTest.zip)

**Comment by bsavery** [comment]
So basically the light transform isn't being applied to the size of the light?  Ok, that should be an easy fix.

**Comment by radon199** [comment]
The light will scale if you change the scale, but it doesn't match how big the light should be according to Renderman21.0, and Maya's viewport for the same light.

Because USD has no GL visualization of usdLuxLights yet, Renderman for Maya is the only thing I can go on for how big the light should be.

**Comment by bsavery** [comment]
Should be fixed now!

**Comment by radon199** [comment]
Thanks, this is working for me now.
