### ISSUE TITLE
Failed To Create MaterialX Node

### ISSUE THREAD

**Issue by AlchemistRS** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#401]
The rpr_materialx_node giving this error with any of the .mtlx files provided in this build?

[RPR ERROR] Failed to create materialX node -- Property not found in UpdateNodeOutput at line 313 of C:\JN\WS\RadeonProRenderUSD_Build\RadeonProRenderUSD\pxr\imaging\rprUsd\materialNodes\rpr\materialXNode.cpp(17132f1)

**Comment by hshakula** [comment]
Most likely it's caused by the wrong installation, how were you installing the RPR plugin?

**Comment by AlchemistRS** [comment]
Thanks, George for your response.

I installed it manually and after using the activate exe instead everything is good now.
