### ISSUE TITLE
Release 2.0 missing Release notes

### ISSUE THREAD

**Issue by U-se** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#402]
Hello,

Thank you for the great work on RPR for Houdini. I was hoping to find a longer list of changes regarding the transition to RPR 2.0 (Northstar I believe). Unfortunately, the link on the page is dead:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/releases/tag/v2.0.1

This is the link that's embedded in the Post: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/master/CHANGELOG.md#version-20

Could you update the link, or is there no public list of changes?

**Comment by bsavery** [comment]
Sorry about that.  Here's the correct release notes https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/master/CHANGELOG.MD#version-20
