### ISSUE TITLE
hdRpr Disappearing after picking renderer.

### ISSUE THREAD

**Issue by cabraswel** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#403]
I have been using Pro render with Houdini since the first one and now I am using the installer script with H18.5.404 using Steam and everything appears to be working much easier that previous versions. But RPR will not work in the viewport after being selected.

I verified that RPR_for_Houdini is in the user folder under packages in the documents\\houdini18.5 folder. I made sure to give my install directory a clean name c:/AMD/hdRpr2_0_1. Since H18.5 I did not have a previous version of RPR installed.

There is also "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\bin\usd_plugins\hdRpr" that seems to be in the proper place.

The issues is when I pick RPR from the render dropdown in the viewport on USD Stage RPR just disappears from the list leaving OGL Karma and storm until I restart Houdini. I can even go in and change the RPR setting if I press "D" in the viewport. But as soon as i pick it as a rendering engine it vanishes. I even tried to switch to "CPU" ahead of picking it.

**Comment by hshakula** [comment]
This sounds like a typical example of a mismatch of dynamic libraries required by the plugin and libraries of the current Houdini in use. It happens when you use hdRpr that was compiled against another Houdini version.

So I decided to check if H18.5.404 works with the plugin built against H18.5.351 (the latest production release). But what's interesting, for me, RPR was not visible at all. For some reason, H18.5.404 required me to substitute `$RPR` in the plugin package json by hand, so that this
```
{"env":[{"RPR":"some-path"},{"HOUDINI_PATH":"$RPR/houdini"},{"PATH":"$RPR/lib"},{"PYTHONPATH":"$RPR/lib/python"}]}
```
becomes this
```
{"env":[{"RPR":"some-path"},{"HOUDINI_PATH":"some-path/houdini"},{"PATH":"some-path/lib"},{"PYTHONPATH":"some-path/lib/python"}]}
```

And so I was able to reproduce your issue, I see what is causing this, I will fix it. But in the meantime, you can play with this [build](https://drive.google.com/file/d/1GNNsp0xVk4Ef5vNYRkgIkQNriudZcACT/view?usp=sharing)

**Comment by hshakula** [comment]
> There is also "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie\bin\usd_plugins\hdRpr" that seems to be in the proper place.

There should not be any hdRpr files in your Houdini. We don't install hdRpr in the Houdini installation directory anymore because it requires you to reinstall it each time you update Houdini.

**Comment by cabraswel** [comment]
Thank you.

**Comment by cabraswel** [comment]
I am having the same problem. I tried H.18.5.351 and H.18.5.404. I am not not sure why. I even deleted houdini and reinstalled it. RPR shows up then vanishes when I try to use it. I even get the RPR menu at the top near the file menu.

**Comment by hshakula** [comment]
That's definitely an issue caused by a mismatch of dynamic libraries. Let's try to figure out what's going on. Please set the environment variable TF_DEBUG to TF_DLOPEN value and try enabling RPR. You should see some sort of such output: 
![image](https://user-images.githubusercontent.com/22181845/100104238-979f1e80-2e6e-11eb-813d-615e7109c9e5.png)
And there should be a line with hdRpr. Send me your output.

If you see a load error then do the following:

* download dependency walker - https://www.dependencywalker.com/.

* run it from Houdini:
    ![image](https://user-images.githubusercontent.com/22181845/100104601-13996680-2e6f-11eb-8cde-168cb92a36c9.png)
    ```
    import subprocess
    subprocess.check_output(r'D:\Downloads\depends22_x86\depends.exe')
    ```
    **insert your path to depends.exe**

* open `c:/AMD/hdRpr2_0_1/plugin/usd/hdRpr.dll`. You should see something like this:
    ![image](https://user-images.githubusercontent.com/22181845/100104988-81de2900-2e6f-11eb-963f-d15e9704f3b5.png)

* press `ctrl+w` and expand the top-most element and send me what you see. Example:
    ![image](https://user-images.githubusercontent.com/22181845/100105128-adf9aa00-2e6f-11eb-9c42-338432b9c0c7.png)

**Comment by cabraswel** [comment]
I was unable to find the debug outputl. I found the .h files for USD but did not know which of the 3 needed the variable to be set so i just did a screen grab for you anyway.

![Screen](https://user-images.githubusercontent.com/11642840/100144429-9f010080-2e4b-11eb-8541-fcf212345c40.png)

**Comment by hshakula** [comment]
Debug output? Do you mean console?
Did you set TF_DEBUG=TF_DLOPEN as stated [here](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)?

From the screenshot, I see that hdRpr should load, weird. Can you check if RPRUSD.dll has any missing dependencies? Just to be sure? (red entries)

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100159903-7d137800-2e63-11eb-981a-32c28aa9b12e.png)

![image](https://user-images.githubusercontent.com/11642840/100159952-8ef51b00-2e63-11eb-9b30-427d5a1538f4.png)

**Comment by hshakula** [comment]
>I edited the environment variables and I hope that is correct. I do not get any outputs when i change to RPR in the viewport so I wonder if I did that correctly.

To apply changes of environment you need to press ok:
![image](https://user-images.githubusercontent.com/22181845/100212626-434f7980-2f16-11eb-8c68-9480a44e1169.png)

and restart Houdini.

And for rprusd.dll, could you please screenshot this just like you did it for hdRpr.dll (with all second-level dependencies collapsed)?

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100276762-e7d1bb80-2f16-11eb-8257-dfb49bea272c.png)
![image](https://user-images.githubusercontent.com/11642840/100276826-ff10a900-2f16-11eb-90c5-c90f0ff7dd4a.png)

**Comment by hshakula** [comment]
That's really weird, let's make sure that it tries to load correct libraries. Could you please make the same screenshot as you did here https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/403#issuecomment-733198803 but with `View Full Paths`:
![image](https://user-images.githubusercontent.com/22181845/100278719-01eab880-2f6e-11eb-8151-1172d697621a.png)

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100289155-21152600-2f2d-11eb-9d86-d1d242fbaa7d.png)

**Comment by hshakula** [comment]
Please collapse second-level entries

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100290117-65a1c100-2f2f-11eb-989c-b1a3fd02c14a.png)

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100290330-f11b5200-2f2f-11eb-8164-8a6242ec3a14.png)

**Comment by hshakula** [comment]
The only weird thing I see here is that your houdini uses python27.dll from system32 instead of using its own one. But I don’t think that it causes our issue.

Do you see any red dll entries in dependency walker? (If you expand all dll entries)

**Comment by cabraswel** [comment]
I explored doing a page down in multiple windows and I found IEframe, SCHcore SCHLwapi are red.
![image](https://user-images.githubusercontent.com/11642840/100293274-01372f80-2f38-11eb-8025-5c39ab7bc560.png)
![image](https://user-images.githubusercontent.com/11642840/100293311-1c09a400-2f38-11eb-8fc0-9c2d05e805fd.png)

**Comment by hshakula** [comment]
Hm, but these libraries are not in direct dependencies of hdRpr. Could you please find who relies on one of them (in the dll tree)? Most likely it will one of system32 libraries. And if you will find it, select it and make a screenshot pls

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100296777-f84b5b80-2f41-11eb-9560-c3c0c7b76d52.png)

**Comment by cabraswel** [comment]
![image](https://user-images.githubusercontent.com/11642840/100296835-13b66680-2f42-11eb-95f2-479338af1e57.png)

**Comment by hshakula** [comment]
I still did not get what exactly prevents hdRpr to load. Can I get remote access to your dependency walker to inspect it more thoroughly?

**Comment by cabraswel** [comment]
Could we use a screen share with discord?

**Comment by cabraswel** [comment]
I have done a clean install of Houdini and a clean install of hdRpr and still no dice. I am using Houdini with Python 2.7 and everything else seems to work USD related.

TfDlopen: [opening] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_Plugins.dll' (flag=0)...
TfDlopen: [opened] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_Plugins.dll' (handle=00000000B3850000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_usd.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_usd.dll' (handle=00007FF80BCB0000)
TfDlopen: [opening] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_NC.dll' (flag=0)...
TfDlopen: [opened] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_NC.dll' (handle=000000009FAC0000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_sdf.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_sdf.dll' (handle=00007FF80B910000)
TfDlopen: [opening] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_Plugins.dll' (flag=0)...
TfDlopen: [opened] 'c:/PROGRA~2/Steam/STEAMA~1/common/HOUDIN~1/houdini/dso/usd/USD_Plugins.dll' (handle=00000000B3850000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/usd_plugins/hdStorm.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/usd_plugins/hdStorm.dll' (handle=00007FF88A7F0000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_hgiGL.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_hgiGL.dll' (handle=00007FF85DDD0000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_glf.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_glf.dll' (handle=00007FF82C4B0000)
TfDlopen: [opening] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_usdImaging.dll' (flag=0)...
TfDlopen: [opened] 'c:/Program Files (x86)/Steam/steamapps/common/Houdini Indie/bin/libpxr_usdImaging.dll' (handle=00007FF80B1A0000)
TfDlopen: [opening] 'c:/AMD/hdRpr/plugin/usd/hdRpr.dll' (flag=0)...
TfDlopen: [opened] 'c:/AMD/hdRpr/plugin/usd/hdRpr.dll' (handle=0000000000000000)
TfDlopen: [error on opening] 'c:/AMD/hdRpr/plugin/usd/hdRpr.dll': The specified procedure could not be found.

**Comment by zxzxde** [comment]
I have the same problem 
![rpr](https://user-images.githubusercontent.com/16136264/111406438-46f94d00-870d-11eb-978a-d8345e4625eb.gif)

**Comment by PatrickZeller** [comment]
also have the same issue

![image](https://user-images.githubusercontent.com/31572715/112054692-276f8380-8b56-11eb-8b46-a8a1de588409.png)
thats an error message when i press something in the RPR menu

**Comment by hshakula** [comment]
> also have the same issue
> 
> ![image](https://user-images.githubusercontent.com/31572715/112054692-276f8380-8b56-11eb-8b46-a8a1de588409.png)
> thats an error message when i press something in the RPR menu
> 
> oh and i tried to use both 18.5.408 same error.

Do you have any other plugins that require houdini.env modifications?

**Comment by hshakula** [comment]
> I have the same problem
> ![rpr](https://user-images.githubusercontent.com/16136264/111406438-46f94d00-870d-11eb-978a-d8345e4625eb.gif)

You are using hdRpr build for Houdini 18.5.408 in Houdini 18.5.509. Seems like these two versions are not compatible. You have a few options:
* try a build from this comment - https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/441#issuecomment-784995592
* use Houdini 18.5.408
* wait for the next release (should be on this week)

**Comment by bsavery** [comment]
Hi @cabraswel  or others.  Can you retry with latest build?  Reopen if still seen.
