### ISSUE TITLE
Shading is flat; normals aren't interpolated

### ISSUE THREAD

**Issue by trebconnell** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#435]
This image taken from Usd kitchen_set scene, Quality: Northstar, but also reproduces using 'Medium' quality

Platform: Windows
RprUsd Ver: 2.0.19 (f9d793d)
Usd Ver: v20.11

![image](https://user-images.githubusercontent.com/6809385/105434009-96406700-5c0f-11eb-9185-4210cb1ac683.png)

**Comment by hshakula** [comment]
With RPR delegate it was preferable to explicitly control the level of subdivision. But that was back in the days. Now we can try to roll out automatic subdivision. I will implement it.

Low-High qualities do not support subdivision for now.

**Comment by trebconnell** [comment]
Thanks, but I believe this should be able to be fixed by using a different shading model which interpolates normals across the face. Ex: https://en.m.wikipedia.org/wiki/Shading

**Comment by hshakula** [comment]
@trebconnell, please have a look at the images from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/436

**Comment by trebconnell** [comment]
Thanks! Those look great. Thanks for fast turn around here! 
The ability to subdiv will also be useful.

**Comment by hshakula** [comment]
We have subdivision feature available with "Full" and "Full (Legacy)" qualities. You just need to create `rpr:subdivisionLevel` int primvar on a mesh. See example - [subdivisionSample.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/5858696/subdivisionSample.zip)

Let me know if you require subdivision in Low-High qualities.
