### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by LucaPrassoDaydreamLabs** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#441]
I've installed hdRpr-2.0.13-Houdini-18.5.408-py3.7-Windows, added the proper package JSON file to Houdini package folder but every time I start Houdini 408 (or greater) I get a popup message stating that the RPR_for_Houdini.dll could not be loaded

I checked the file path and JSON file multiple times (and even installed using the provided script).
The same installation works fine on my Mac laptop.

![RPR_DSO_Error](https://user-images.githubusercontent.com/11843422/108917299-5ee52180-75e4-11eb-92a1-f249a0ce098e.PNG)

Any idea of what I'm doing wrong?

Thanks,
Luca

**Comment by bsavery** [comment]
What version Houdini do you have?

**Comment by bsavery** [comment]
Also there are python 2 and python 3 versions of Houdini.  Make sure you have the right build.

**Comment by LucaPrassoDaydreamLabs** [comment]
I have Houdini 18.5.408 Python3 and 18.5.462 Python 3 installed.
Both of them show the same popup at startup.

To make things even more puzzling.
I just installed Octane's Hydra delegate. It requires editing houdini.env to edit PATH and HOUDINI_PATH (no installation via packages).
When these variables are pointing to the Octane Hydra install, RPR error does not pop up and I have no RPR menu.
If I comment the Octane variables, I get the popup errors and the RPR menu (but no way to use RPR in Solaris).

**Comment by hshakula** [comment]
Hey Luca, please, try this [build](https://drive.google.com/file/d/1UrwZR4_K_6l_TETuKSOvisrxy1rwx1F9/view?usp=sharing)

**Comment by LucaPrassoDaydreamLabs** [comment]
Works on 18.5462! Thanks George!
