### ISSUE TITLE
two known issues in 2.0.27

### ISSUE THREAD

**Issue by wongdi** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#453]
hdRpr-2.0.27-Houdini-18.5.499-py2.7-macOS

macOS big sur 11.2.3

houdini 18.5.499
----------------------------------------------

1.  Import Material crash.

![WechatIMG22](https://user-images.githubusercontent.com/61398882/113479658-e9ae1b80-94c2-11eb-99b6-0f3af4b9b143.png)

2. Do not display objects when moving the view.

![WechatIMG20](https://user-images.githubusercontent.com/61398882/113479691-12ceac00-94c3-11eb-9a39-b872b40a8286.png)

![WechatIMG21](https://user-images.githubusercontent.com/61398882/113479699-1d894100-94c3-11eb-8a14-08f53fc8fa7e.png)

**Comment by hshakula** [comment]
1. I'll check.
2. I've reported it to the core team, hopefully will be fixed in the next release of RPR SDK. As a temporary workaround, you may disable alpha - in "Render Settings" uncheck "Enable Color Alpha".

**Comment by wongdi** [comment]
> 1. ‎我会检查的‎
> 2. I've reported it to the core team, hopefully will be fixed in the next release of RPR SDK. As a temporary workaround, you may disable alpha - in "Render Settings" uncheck "Enable Color Alpha".

thk 😄

**Comment by hshakula** [comment]
@wongdi, I have fixed the first issue. I can create a build for you. If you are interested, let me know Houdini and python versions you need

**Comment by wongdi** [comment]
> @wongdi, I have fixed the first issue. I can create a build for you. If you are interested, let me know Houdini and python versions you need

I use houdini 18.5.449 and Python 2.7 under macOS 11.2.3 ,thank you for your work😁

**Comment by hshakula** [comment]
It's impossible to download this particular version from sidefx.com. So here a [build for H18.5.462-py2](https://drive.google.com/file/d/1qB89e8ikcNzggnLGy2TXBQwWnpAFa0mq/view?usp=sharing)

**Comment by wongdi** [comment]
> It's impossible to download this particular version from sidefx.com. So here a [build for H18.5.462-py2](https://drive.google.com/file/d/1qB89e8ikcNzggnLGy2TXBQwWnpAFa0mq/view?usp=sharing)

oh sorry，houdini is 18.5.499，maybe it can be used。。。

**Comment by hshakula** [comment]
If you have not yet downloaded the .mtlx version of the RPR Material library, you will be redirected to a guide that is not yet in master. That's simply because this PR https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/464 is not yet merged to master. Here is the correct link for now - https://github.com/hshakula/RadeonProRenderUSD/tree/simplify-matlib-install#rpr-material-library (the bottom of the page)

And here is a build for 18.5.499 - https://drive.google.com/file/d/1RwI0HuTpEhvdfqv8xDzGp6VgySRubYFx/view?usp=sharing

**Comment by wongdi** [comment]
> If you have not yet downloaded the .mtlx version of the RPR Material library, you will be redirected to a guide that is not yet in master. That's simply because this PR #464 is not yet merged to master. Here is the correct link for now - https://github.com/hshakula/RadeonProRenderUSD/tree/simplify-matlib-install#rpr-material-library (the bottom of the page)
> 
> And here is a build for 18.5.499 - https://drive.google.com/file/d/1RwI0HuTpEhvdfqv8xDzGp6VgySRubYFx/view?usp=sharing

I did some tests this morning and it took a while to solve the "@" permission issue, now it works fine, thk bro🙏

**Comment by hshakula** [comment]
What the "@" permission issue is about? Could you please elaborate?

**Comment by wongdi** [comment]
typical problems on big sur，*.dylib and _rprUsd.so will appear this prompt


![WX20210420-202928](https://user-images.githubusercontent.com/61398882/115396060-2c882700-a217-11eb-8372-50caa7db9d6a.png)



> What the "@" permission issue is about? Could you please elaborate?

**Comment by wongdi** [comment]
> If you have not yet downloaded the .mtlx version of the RPR Material library, you will be redirected to a guide that is not yet in master. That's simply because this PR #464 is not yet merged to master. Here is the correct link for now - https://github.com/hshakula/RadeonProRenderUSD/tree/simplify-matlib-install#rpr-material-library (the bottom of the page)
> 
> And here is a build for 18.5.499 - https://drive.google.com/file/d/1RwI0HuTpEhvdfqv8xDzGp6VgySRubYFx/view?usp=sharing



I may get an empty material。。。

![WX20210420-204104](https://user-images.githubusercontent.com/61398882/115397704-f77cd400-a218-11eb-8446-db7af7fe93a2.png)

![WX20210420-204139](https://user-images.githubusercontent.com/61398882/115397870-209d6480-a219-11eb-9706-a790117cd48a.png)

![WX20210420-204334](https://user-images.githubusercontent.com/61398882/115397889-25621880-a219-11eb-9d10-6e7890be4c6f.png)

**Comment by hshakula** [comment]
This build should work - https://drive.google.com/file/d/1ZfptjdWT9GpAvmsfBjCZzWjRa1Pq0VK3/view?usp=sharing. This build also includes changes from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/465.

Are you using the py2 version, right?

**Comment by wongdi** [comment]
> This build should work - https://drive.google.com/file/d/1ZfptjdWT9GpAvmsfBjCZzWjRa1Pq0VK3/view?usp=sharing. This build also includes changes from #465.
> 
> Are you using the py2 version, right?

yes. I use python 2.7 version

**Comment by wongdi** [comment]
> This build should work - https://drive.google.com/file/d/1ZfptjdWT9GpAvmsfBjCZzWjRa1Pq0VK3/view?usp=sharing. This build also includes changes from #465.
> 
> Are you using the py2 version, right?

![WX20210421-071601](https://user-images.githubusercontent.com/61398882/115475087-756cc980-a271-11eb-846a-0125a447bcf2.png)


thk bro，it worked perfectly😊
