### ISSUE TITLE
The link to `Material Library` is broken

### ISSUE THREAD

**Issue by hatoo** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#480]
Hi, 
I want to use `Material Library` in the Houdini plugin but I couldn't download it with [the link described in Pluginin's message](https://drive.google.com/file/d/1e2Qys1UMi9pu_x3wW5ctm9b8_FIohLKG/view?usp=sharing).
Is there any other source to download `Material Library`?

**Comment by hshakula** [comment]
The information provided in the releases is outdated.

`Material Library` installation was changed. This change will be in the next release (ETA this week).

If you wish I can make you a recent build. If so, let me know your platform and Houdini version.

**Comment by hatoo** [comment]
Thanks, I'll wait for the next release.

**Comment by hshakula** [comment]
Hey, @hatoo, please let us know how it goes for you with [the latest release](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/releases/tag/v2.2.0) - link to the material library at the bottom of the README file.

**Comment by hatoo** [comment]
Thanks, @hshakula.
I've succeeded to use the `Import Material` feature in the latest release:thumbsup:.
