### ISSUE TITLE
Crash when RPR is selected as renderer

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#482]
Hi,

For some reason when I switch the viewport render to RPR, I get this error and Houdini completely crashes:
![image](https://user-images.githubusercontent.com/51461775/124599231-6ee2fc80-de33-11eb-97bf-124489bdec33.png)
I've reinstalled RPR and I've tried doing older builds of Houdini and newer builds and Python 2.7 and 3.7, but they all seem to have the same issue. What is weird is that it seemed to just start all of a sudden despite having changed nothing about my system or anything.

I also tried rendering to disk without turning on viewport render, and it wouldn't write out any file and similarly when I rendered to MPlay, it just put out a black frame.

**Comment by hshakula** [comment]
> despite having changed nothing about my system or anything

Are your GPU drivers also unchanged from the time RPR was working?

**Comment by AlxndrTheWretch** [comment]
I had forgotten about that actually, I am using the Studio Drivers from NVIDIA but I tried going back one release to see and now it is working. So I guess it was just the drivers...

**Comment by hshakula** [comment]
FYI the next hdRpr release should fix this issue for the recent driver.

https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/481
