### ISSUE TITLE
Light Linker not working

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#492]
Hi,

I'm trying to have a backdrop using geometry outside a window and having a sun shine through the window as well so I am trying to use the light linker to create a shadow rule that the backdrop won't cast shadows, it works in karma:
![image](https://user-images.githubusercontent.com/51461775/126328648-d4fff475-72e0-46dd-9487-c11ac4e8e399.png)

But not in RPR:
![image](https://user-images.githubusercontent.com/51461775/126328457-dc9816a5-8661-45a8-92bd-f46f21132452.png)

Is there a different way to accomplish this or will this be supported in the future? Thanks! (really enjoying RPR)

**Comment by hshakula** [comment]
RPR does not support the light linker.

You can try to make your backdrop invisible for shadow rays:

![image](https://user-images.githubusercontent.com/22181845/126498763-0cddb83f-0791-48bc-93a7-8259d3b00d07.png)

Here is a sample project: [backdropTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6856191/backdropTest.zip). Let me know if it fits your needs.

**Comment by AlxndrTheWretch** [comment]
That did what I needed, thanks!
