### ISSUE TITLE
VDB / Volume Color

### ISSUE THREAD

**Issue by petermandk** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#495]
Is it possible to set up color to smoke/vdb for example blue or red? I was looking around but can not find any topic covering this so my brain can clearly understand how to do it. Attached is my actual setup, I managed to figure out how to create volume in RPR, but no luck with color so far.

https://drive.google.com/file/d/1_fTHZOU4zlW3PhPUnhEox5758TwC8l-i/view?usp=sharing

**Comment by hshakula** [comment]
With the current version, you have to define a color grid with an appropriate color ramp. This is not really convenient if you just want to make volume single-colored, too much hustle for such an easy task. So I revised `bias` and `gain` parameters a bit and now you can accomplish it using them.

Here's your project that I modified a bit: [RPR_smoke_color.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6874597/RPR_smoke_color.zip)
![output](https://user-images.githubusercontent.com/22181845/126914198-f4dd8f8c-ad46-4c23-b70d-153d69724664.png)

But you also need the updated plugin. Let me know your platform and houdini version (including python version).

**Comment by petermandk** [comment]
Win Houdini 18.5.596 Py3

**Comment by hshakula** [comment]
https://drive.google.com/file/d/12MpmkMzg-QANEHst_A4q-g5srHGFCYP_/view?usp=sharing

**Comment by petermandk** [comment]
From name I assume its for macOS, but I unfortunately use Windows.

**Comment by hshakula** [comment]
Oops, somehow I mixed them up

https://drive.google.com/file/d/1x6-gRFFzGzcOltMNHAvo1uPurGHFEvkj/view?usp=sharing

**Comment by petermandk** [comment]
Thank you very much, this works like charm. One strange thing happens with this new version everytime I turn on denoising I get this error and rendering stops. Without denoising everything is fine. 

[ERROR@RIF]: File not found: c:/Users/Admin/Documents/houdini18.5/hdRpr-2.2.6-Houdini-18.5.596-py3.7-Windows/plugin/usd/hdRpr/resources/rif_models/denoise_c9_hdr_gamma_2.5.pb at file C:\JN\WS\RadeonProImageProcessor_Build\src\AIFilters.cpp line 258

**Comment by hshakula** [comment]
Please open new issue, this can be closed I suppose
