### ISSUE TITLE
UsdPreviewSurface renders black except for emissiveColor

### ISSUE THREAD

**Issue by radon199** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#5]
Hey,

This is using the pre-built example for windows.

I am unable to get a UsdPreviewSurface to display anything other than black, except for emissiveColor, which works as expected.

I get no specular with either specular or metalic, and no diffuse color.

I get no errors in the shell from UsdView.

I have included my test file below.

[dragon.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/2342104/dragon.zip)

**Comment by bsavery** [comment]
Should be fixed now!

**Comment by radon199** [comment]
Thanks, this is working for me now.
