### ISSUE TITLE
Houdini: big difference in light intensity between hdRpr and hdKarma

### ISSUE THREAD

**Issue by hshakula** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#51]
### Description of Issue
On the scene with some lights (e.g. light or dome), we have a big difference in light intensity. To make the intensity of the same level we need to set intensity approximately 10x times less for hdRpr. Also, it looks like hdKarma's 'Normalize power' checkbox does something different than hdRpr, but it may be that it seems like this due to a problem with the intensity

### System Information (OS, Hardware)
Windows

### Package Versions
Houdini 18.0.236

**Comment by bsavery** [comment]
So normalize should not effect dome lights.  Correct?  

One question is how the Karma sets resulting intensity.  It should be (and what RPR was supposed to be doing was)
resulting_power = intensity * 2 ^ exposure / (area scaled by transform)

**Comment by hshakula** [comment]
The dome light is affected by 'Normalize power' neither in hdRpr nor in hdKarma.
I said a little wrong. The difference between dome lights is in an exposure. If exposure is zero, we have the smallest difference in intensity, but the bigger exposure the greater the difference in resulting image
Here are some images of the same scene with sphere light and dome light [images.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3682187/images.zip)

For sphere light, you can see that without "Normalize power" we have approximately the same intensity, but when it's enabled difference is huge

**Comment by bsavery** [comment]
Hmmmm.  

1.  The karma exposure looks more linear than exponential to me.  Do you agree?  I might file this as a bug to them.
2.  Normalize it looks like ours gets brighter with normalization while theirs dims.  What is the size / transform of the lights in this case?  Or is the 32.5 the radius?  Note the transform scale has to be taken into account.

**Comment by hshakula** [comment]
1. The rate of change in intensity is definitely closer to linear than to exponential
2. I am going to debug normalization tomorrow

**Comment by hshakula** [comment]
Okay, I have debugged normalization and I don't see anything wrong in our computations.
But here is an interesting thing in karma. Look at those images: [images1.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3686671/images1.zip).
Two renders from hdKarma, same radius, same intensity, but one with normalization and second without it. They are same, while the radius of the sphere is 0.3
Not 1.0, not even 0.5, but 0.3! What's going on here?

**Comment by bsavery** [comment]
Actually I *think* they are slightly different.  The un-normalized looks slightly brighter.

**Comment by hshakula** [comment]
Ok, I will try radius 1/3

**Comment by bsavery** [comment]
Also WRT to the dome light.  It looks like we don't get the color or temperature from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/ffbcb8a9013b0baf855f795d8f85a34a28cf8aa7/pxr/imaging/plugin/hdRpr/domeLight.cpp#L57

**Comment by hshakula** [comment]
I've made screenshots using build with those changes otherwise it would be our default light color because dome light previously was working only with textures

**Comment by bsavery** [comment]
Do we think we should close this?

**Comment by hshakula** [comment]
For now, I don’t see any more intensity issues. I will recheck old assets to ensure problem absence

**Comment by hshakula** [comment]
I have tested again the same problematic assets with the latest Houdini version (18.0.286).
Karma does not see any lights and renders a pure ambient occlusion image. On the other hand, all the latest assets I have worked with do not have such lighting issues. Closing this issue as outdated.
