### ISSUE TITLE
Houdini: add ability to change render device and render quality

### ISSUE THREAD

**Issue by hshakula** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#52]
### Description of Issue
The actual issue here is to found out the way how could we reemit a scene after render device change to setup scene for a newly created context

**Comment by hshakula** [comment]
Currently, there is no non-ugly way to implement a scene reemit in Houdini from the plugin side. The only way to reemit the scene is to restart renderer using Houdini UI (have a look at the attached image). 
![ui](https://user-images.githubusercontent.com/22181845/68674654-f1cc8a80-055e-11ea-8a9d-ff486f0b65d8.png)

So I propose such workaround if user changes render device or render quality: instead of rendering scene, render image asking for render restart. Of course, we would not do it when user change render quality in the range of low-high, i.e. Hybrid qualities.

P.S. the ugly way I was talking about is to store pointers to all primitives inside of render delegate and try to manually simulate scene reemit by calling Sync methods with AllDirty dirtyBits

**Comment by bsavery** [comment]
ok.  that workaround sounds fine

> instead of rendering scene, render image asking for render restart.
