### ISSUE TITLE
Rpr render is offset vertically by the width of a USD camera mask

### ISSUE THREAD

**Issue by radon199** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#6]
Hey,

Rpr will render a masked camera, but the image in the USDView viewer is offset vertically by the width of the camera mask.

Without a camera mask the Rpr render will line up visually with the gl render.

This is from the binary on the AMD website.

![usdcameracrop](https://user-images.githubusercontent.com/39324245/44948510-62acda00-add3-11e8-9e0d-77d43bb9a187.jpg)

![rprcameracrop](https://user-images.githubusercontent.com/39324245/44948513-680a2480-add3-11e8-9aef-7c8164efa357.jpg)

-Colin

**Comment by bsavery** [comment]
When you say a masked camera, do you have an example of a file with that?  Not something we tested before extensively

**Comment by radon199** [comment]
Sure. It's Masked to only show the filmgate in the viewport. In this case an anamorphic lens.

[camera_fg.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/2345845/camera_fg.zip)

Also, to enable the mask in the viewport go to this menu option in USD view : 

**View > Camera Guides > Camera Masking > Full Mask**

This will show a colored border and restrict the USD view window to the masked view, as in the above screenshots.

UsdView's usdviewApi.viewportSize still returns the same value when masked or not, which is interesting.
