### ISSUE TITLE
Compile errors with debug configuration on Windows

### ISSUE THREAD

**Issue by minghao-AMD** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#83]
While release configuration is building fine, debug configuration is getting some compile errors which all point to the same tbb header in usd.
Would be great to have this fixed since they would help debugging a lot.

5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\renderBuffer.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\domeLight.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\materialFactory.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\materialAdapter.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\rendererPlugin.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\renderDelegate.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\volume.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\material.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\lightBase.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\field.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\rectLight.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\sphereLight.cpp)
5>d:\usdbin\include\tbb\tbb_profiling.h(55): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\rprApi.cpp)
5>d:\usdbin\include\tbb\internal\_concurrent_queue_impl.h(475): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\basisCurves.cpp)
5>d:\usdbin\include\tbb\internal\_concurrent_queue_impl.h(475): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\renderPass.cpp)
5>d:\usdbin\include\tbb\internal\_concurrent_unordered_impl.h(633): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\mesh.cpp)
5>d:\usdbin\include\tbb\internal\_concurrent_unordered_impl.h(633): fatal error C1017: invalid integer constant expression (compiling source file D:\RadeonProRenderUSD\pxr\imaging\plugin\hdRpr\instancer.cpp)

**Comment by hshakula** [comment]
I did not find out the cause of this problem, but I can advise something to get around this issue and get debug build.
Add ‘add_definitions(-DTBB_USE_DEBUG=0)’ to cmake
