### ISSUE TITLE
Lights only respect local and not world transforms.

### ISSUE THREAD

**Issue by radon199** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#9]
This is an issue discovered in part due to PR #7.

It seems that all lights in USD, when imaged, will only respect their local transform. This is true for lights imaged with hdSt or hdRpr.

This is the light transform function of hdSt light.cpp on the Pixar repo, there is also a similar function in the lightBase.cpp file of hdRpr

Pixar hdStream repo : 
// Transform if (bits & DirtyTransform) { VtValue transform = sceneDelegate->Get(id, HdLightTokens->transform);
if (transform.IsHolding<GfMatrix4d>()) { _params[HdLightTokens->transform] = transform; } else { _params[HdLightTokens->transform] = GfMatrix4d(1); } }
hdRpr repo : 
`VtValue transformValue = sceneDelegate->Get(id, HdLightTokens->transform);
GfMatrix4d transform = (transformValue.IsHolding<GfMatrix4d>()) ? transformValue.Get<GfMatrix4d>() : GfMatrix4d(1);`

There is a GetTransform() function in the sceneDelegate but that only works on rprims, and lights are sprims.

Therefore we need to use the Get() function and ask for the transform. This has the side effect of only getting the local transform and not the global transform down to the root.

I have included a file below that demonstrates this. In it the sphere and the light on the grid should be in the same place as they have the same transforms, but they are not, the light only respects it's own local transform relative to the world. This is the same in both hdStream and hdRpr.

I will file a ticket with Pixar.

lightTransformTest.zip

**Comment by radon199** [comment]
Issue added to USD Repo.

https://github.com/PixarAnimationStudios/USD/issues/612#issue-357907677

**Comment by sayakbiswas** [comment]
Nice, saw that they've fixed it internally. Will review and merge this once that is released.

**Comment by bsavery** [comment]
Closing since merged!
